# Исследование надежности заемщиков.

### 0.1 Шаг 1. Обзор данных

In [1]:
import pandas as pd
data = pd.read_csv('data.csv')

print('Информация о датафрейме:')
data.shape

Информация о датафрейме:


(21525, 12)

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21525 non-null  int64  
 1   days_employed     19351 non-null  float64
 2   dob_years         21525 non-null  int64  
 3   education         21525 non-null  object 
 4   education_id      21525 non-null  int64  
 5   family_status     21525 non-null  object 
 6   family_status_id  21525 non-null  int64  
 7   gender            21525 non-null  object 
 8   income_type       21525 non-null  object 
 9   debt              21525 non-null  int64  
 10  total_income      19351 non-null  float64
 11  purpose           21525 non-null  object 
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB


In [3]:
display(data.head(10))

children  days_employed  dob_years education  education_id  \
0         1   -8437.673028         42    высшее             0   
1         1   -4024.803754         36   среднее             1   
2         0   -5623.422610         33   Среднее             1   
3         3   -4124.747207         32   среднее             1   
4         0  340266.072047         53   среднее             1   
5         0    -926.185831         27    высшее             0   
6         0   -2879.202052         43    высшее             0   
7         0    -152.779569         50   СРЕДНЕЕ             1   
8         2   -6929.865299         35    ВЫСШЕЕ             0   
9         0   -2188.756445         41   среднее             1   

      family_status  family_status_id gender income_type  debt   total_income  \
0   женат / замужем                 0      F   сотрудник     0  253875.639453   
1   женат / замужем                 0      F   сотрудник     0  112080.014102   
2   женат / замужем                 0      M   сотрудник     0  145885.952297   
3   женат / замужем                 0      M   сотрудник     0  267628.550329   
4  гражданский брак                 1      F   пенсионер     0  158616.077870   
5  гражданский брак                 1      M   компаньон     0  255763.565419   
6   женат / замужем                 0      F   компаньон     0  240525.971920   
7   женат / замужем                 0      M   сотрудник     0  135823.934197   
8  гражданский брак                 1      F   сотрудник     0   95856.832424   
9   женат / замужем                 0      M   сотрудник     0  144425.938277   

                      purpose  
0               покупка жилья  
1     приобретение автомобиля  
2               покупка жилья  
3  дополнительное образование  
4             сыграть свадьбу  
5               покупка жилья  
6           операции с жильем  
7                 образование  
8       на проведение свадьбы  
9     покупка жилья для семьи

### 0.2 Шаг 2.1 Заполнение пропусков

In [4]:
data.isna().sum()   

children               0
days_employed       2174
dob_years              0
education              0
education_id           0
family_status          0
family_status_id       0
gender                 0
income_type            0
debt                   0
total_income        2174
purpose                0
dtype: int64

In [5]:
data[data['days_employed'].isna() | data['total_income'].isna()]

children  days_employed  dob_years education  education_id  \
12            0            NaN         65   среднее             1   
26            0            NaN         41   среднее             1   
29            0            NaN         63   среднее             1   
41            0            NaN         50   среднее             1   
55            0            NaN         54   среднее             1   
...         ...            ...        ...       ...           ...   
21489         2            NaN         47   Среднее             1   
21495         1            NaN         50   среднее             1   
21497         0            NaN         48    ВЫСШЕЕ             0   
21502         1            NaN         42   среднее             1   
21510         2            NaN         28   среднее             1   

               family_status  family_status_id gender  income_type  debt  \
12          гражданский брак                 1      M    пенсионер     0   
26           женат / замужем                 0      M  госслужащий     0   
29     Не женат / не замужем                 4      F    пенсионер     0   
41           женат / замужем                 0      F  госслужащий     0   
55          гражданский брак                 1      F    пенсионер     1   
...                      ...               ...    ...          ...   ...   
21489        женат / замужем                 0      M    компаньон     0   
21495       гражданский брак                 1      F    сотрудник     0   
21497        женат / замужем                 0      F    компаньон     0   
21502        женат / замужем                 0      F    сотрудник     0   
21510        женат / замужем                 0      F    сотрудник     0   

       total_income                           purpose  
12              NaN                   сыграть свадьбу  
26              NaN                       образование  
29              NaN  строительство жилой недвижимости  
41              NaN  сделка с подержанным автомобилем  
55              NaN                   сыграть свадьбу  
...             ...                               ...  
21489           NaN              сделка с автомобилем  
21495           NaN                           свадьба  
21497           NaN        строительство недвижимости  
21502           NaN  строительство жилой недвижимости  
21510           NaN           приобретение автомобиля  

[2174 rows x 12 columns]

In [6]:
data[data['days_employed'].isna() | data['total_income'].isna()].head(30)

children  days_employed  dob_years            education  education_id  \
12          0            NaN         65              среднее             1   
26          0            NaN         41              среднее             1   
29          0            NaN         63              среднее             1   
41          0            NaN         50              среднее             1   
55          0            NaN         54              среднее             1   
65          0            NaN         21              среднее             1   
67          0            NaN         52               высшее             0   
72          1            NaN         32               высшее             0   
82          2            NaN         50               высшее             0   
83          0            NaN         52              среднее             1   
90          2            NaN         35               высшее             0   
94          1            NaN         34               высшее             0   
96          0            NaN         44              СРЕДНЕЕ             1   
97          0            NaN         47               высшее             0   
120         0            NaN         46              среднее             1   
121         0            NaN         29               высшее             0   
135         0            NaN         27              среднее             1   
141         0            NaN         39              среднее             1   
145         0            NaN         62              среднее             1   
174         0            NaN         55               высшее             0   
181         0            NaN         26              среднее             1   
189         1            NaN         30              среднее             1   
205         1            NaN         31               высшее             0   
220         1            NaN         23  неоконченное высшее             2   
241         0            NaN         47              среднее             1   
242         0            NaN         58              среднее             1   
247         1            NaN         60               высшее             0   
250         0            NaN         54               высшее             0   
264         2            NaN         40              среднее             1   
278         1            NaN         23              Среднее             1   

             family_status  family_status_id gender  income_type  debt  \
12        гражданский брак                 1      M    пенсионер     0   
26         женат / замужем                 0      M  госслужащий     0   
29   Не женат / не замужем                 4      F    пенсионер     0   
41         женат / замужем                 0      F  госслужащий     0   
55        гражданский брак                 1      F    пенсионер     1   
65   Не женат / не замужем                 4      M    компаньон     0   
67         женат / замужем                 0      F    пенсионер     0   
72         женат / замужем                 0      M  госслужащий     0   
82         женат / замужем                 0      F    сотрудник     0   
83         женат / замужем                 0      M    сотрудник     0   
90         женат / замужем                 0      F    сотрудник     0   
94        гражданский брак                 1      F    компаньон     0   
96         женат / замужем                 0      F    сотрудник     0   
97         женат / замужем                 0      F    сотрудник     0   
120        женат / замужем                 0      F    сотрудник     0   
121        женат / замужем                 0      F    компаньон     0   
135        женат / замужем                 0      M    компаньон     0   
141       гражданский брак                 1      M    сотрудник     0   
145        женат / замужем                 0      M    пенсионер     0   
174         вдовец / вдова                 2      F    компаньон     0   
181       гражданский брак      

<div class="alert alert-info">
<b>Комментарий студента (по двум таблицам):</b>
<br>Привёл также, помимо полной таблицы с пропусками в строках: days_employed и total_income, ещё таблицу с её первыми 30-тью значениями, чтобы обнаружить не только ожидаемые пропущенные значения (None или NaN), но тексты-заполнители или произвольные значения от создателей таблицы (которые могут испортить значения данных при вычислении статистических функций (особенно при значении: 0)).<br>
</div>

<div class="alert alert-info">
<b>Комментарий студента:</b>  <i>(Ответ на 1-ый вопрос пункта №1, шага №2)</i>
<br>
Пропуски обнаружены в столбцах: days_employed, total_income (причём в равных количествах). Также приведены сведения о количестве пропущенных значений в обоих столбцах (ещё и попарно, во всех строках) и таблицы со всеми строками, где есть пропущенные значения.<br>
<br>
Можно сделать вывод, что единственный элемент в датафрейме, который обозначает пропущенные значения - это элемент NaN.     
<br>
</div>

In [7]:
data.isna().mean()

children            0.000000
days_employed       0.100999
dob_years           0.000000
education           0.000000
education_id        0.000000
family_status       0.000000
family_status_id    0.000000
gender              0.000000
income_type         0.000000
debt                0.000000
total_income        0.100999
purpose             0.000000
dtype: float64

<div class="alert alert-info">
<b>Комментарий студента:</b>
<br>
Вверху обнаружены доли (средние значения) пропущенных значений в каждом столбце: days_employed и total_income.<br>
</div>

In [8]:
def ratio(dataframe):
    column = []
    for item in data.columns:
        if(data[item].isna().sum() != 0):
            column.append(item)
    return column

In [9]:
for value in ratio(data):
    print(f"Доля пропущенных значений в столбце {value} составляет: {data[value].isna().mean():.1%}")

Доля пропущенных значений в столбце days_employed составляет: 10.1%
Доля пропущенных значений в столбце total_income составляет: 10.1%


<div class="alert alert-info">
<b>Комментарий студента: </b>
<br>Хотя в Jupyter Notebook данные выводятся без функции print() (даже если это данные, отличные от датафреймов и cтрок Series), но если написать просто строки, в виде f-строк, с переменными без функции print(), то получится результат с кавычками, например: <br>'Доля пропущенных значений в столбце days_employed составляет: 10.1%'.<br>
<br>И так в последующих записях проектной работы по "Предобработке данных".<br>
</div>

<div class="alert alert-info">
<b>Комментарий студента:</b> <i>(Ответ на 2-ой и 3-ый вопросы пункта №1, шага №2)</i>
<br>Вверху обнаружены доли (средние значения) пропущенных значений в каждом, из столбцов: days_employed и total_income.<br>
<br>Причины появления пропусков данных в строках days_employed, total_income, т.е.: общий трудовой стаж в днях (условно, потому что общий трудовой стаж не может представляет в виде отрицательного числа, но замена общего трудового стажа данных будет проходить в шаге ) и ежемесячный доход, могут быть:<br>
<br>1. Прежде всего, клиенты, кототрые подали заявления в банке не могут сразу получить сведения о доходах или трудовую книжку (или если недавно трудоустроился, то её заверенную копию). 
<br>2. Некоторые лица являются безработными и ищут работу: в центрах службе занятости или самостоятельно через Интернет.  
<br>3. Некоторые лица являются индивидуальными предпринимателями и самозанятыми и работают на себя, а не официально, в различных организациях.
<br>4. Некоторые лица (в большинстве своём компаньоны-женщины, на языке Python, с помощью параеметра query(): data.query('gender == F and income_type == компаньон')) являются домохозяйками (скорее всего с детьми: data.query('children != 0'))      
</div>

<div class="alert alert-info">
<b>Комментарий студента: </b>
<br>После этого комментария и до конца проекта будут впервые взаимодействовать конструкция для выявления потенциальных ошибок try: ... except: ..., где в случае ошибки при выявлении символов, которые вообще не имеет никакого отношения к типам данных float и, тем более, int (например, буквы латиницы и кириллицы, многие специальные символы) пишет одним сообщением о предупреждении в содержании значений столбца 'total_income', например: 'В столбце data_total_income могут быть только значения с плавающей точкой и челочисленные значения!' или 'Обнаружены нечисловые значения в столбце data_total_income!'.<br>
</div>

In [10]:
try:
    data_total_income = pd.to_numeric(data['total_income']).median()
    data_total_income   
except:
    data_total_income = 'В столбце data_total_income могут быть только значения с плавающей точкой и челочисленные значения!'
    data_total_income

In [11]:
data_total_income

145017.93753253992

In [12]:
try:
    data_total_income_mean = pd.to_numeric(data['total_income']).mean()
    data_total_income_mean   
except:
    data_total_income_mean = 'В столбце data_total_income могут быть только значения с плавающей точкой и челочисленные значения!'
    data_total_income_mean

In [13]:
data_total_income_mean

167422.3022081719

<div class="alert alert-info">
<b>Комментарий студента:</b>
<br>Cоздана переменная data_total_income для хранения переменной медианного значения столбца total_income, из датафрейма data для совершения операций последующих функций, например: вставка в пропущенные значения столбец total_income. Но для предовращения "сюрпризов" в столбце total_income презобразуем все значения столбца total_income в тип данных float, с помощью функции pd.to_numeric().<br>
</div>

In [14]:
data.loc[data['total_income'] != data['total_income'], 'total_income'] = data_total_income  
display(data.head(30))

children  days_employed  dob_years            education  education_id  \
0          1   -8437.673028         42               высшее             0   
1          1   -4024.803754         36              среднее             1   
2          0   -5623.422610         33              Среднее             1   
3          3   -4124.747207         32              среднее             1   
4          0  340266.072047         53              среднее             1   
5          0    -926.185831         27               высшее             0   
6          0   -2879.202052         43               высшее             0   
7          0    -152.779569         50              СРЕДНЕЕ             1   
8          2   -6929.865299         35               ВЫСШЕЕ             0   
9          0   -2188.756445         41              среднее             1   
10         2   -4171.483647         36               высшее             0   
11         0    -792.701887         40              среднее             1   
12         0            NaN         65              среднее             1   
13         0   -1846.641941         54  неоконченное высшее             2   
14         0   -1844.956182         56               высшее             0   
15         1    -972.364419         26              среднее             1   
16         0   -1719.934226         35              среднее             1   
17         0   -2369.999720         33               высшее             0   
18         0  400281.136913         53              среднее             1   
19         0  -10038.818549         48              СРЕДНЕЕ             1   
20         1   -1311.604166         36              среднее             1   
21         1    -253.685166         33              среднее             1   
22         1   -1766.644138         24              среднее             1   
23         0    -272.981385         21               высшее             0   
24         1  338551.952911         57              среднее             1   
25         0  363548.489348         67              среднее             1   
26         0            NaN         41              среднее             1   
27         0    -529.191635         28               высшее             0   
28         1    -717.274324         26               высшее             0   
29         0            NaN         63              среднее             1   

            family_status  family_status_id gender  income_type  debt  \
0         женат / замужем                 0      F    сотрудник     0   
1         женат / замужем                 0      F    сотрудник     0   
2         женат / замужем                 0      M    сотрудник     0   
3         женат / замужем                 0      M    сотрудник     0   
4        гражданский брак                 1      F    пенсионер     0   
5        гражданский брак                 1      M    компаньон     0   
6         женат / замужем                 0      F    компаньон     0   
7         женат / замужем                 0      M    сотрудник     0   
8        гражданский брак                 1      F    сотрудник     0   
9         женат / замужем                 0      M    сотрудник     0   
10        женат / замужем                 0      M    компаньон     0   
11        женат / замужем                 0      F    сотрудник     0   
12       гражданский брак                 1      M    пенсионер     0   
13        женат / замужем                 0      F    сотрудник     0   
14       гражданский брак                 1      F    компаньон     1   
15        женат / замужем                 0      F    сотрудник     0   
16        женат / замужем                 0      F    сотрудник     0   
17       гражданский брак                 1      M    сотрудник     0   
18         вдовец / вдова                 2      F    пенсионер     0   
19              в разводе                 3      F    сотрудник     0   
20        женат / замужем                 0      M    сотрудник     0   
21       г

<div class="alert alert-info">
<b>Комментарий студента:</b>
<br>
Созданы обновлённые датафреймы data и data_mean (конечно дальше будем использовать только датафрейм data), специально с функцией .head(30) (вывода первых 30 строк), для проверки правильности выполнения заполнения пропущенных данных столбца total_income.<br>
</div>

In [15]:
data_total_income = data['total_income'].median()
data_total_income

145017.93753253992

In [16]:
data_total_income_mean = data['total_income'].mean()
data_total_income_mean

165159.4873972547

In [17]:
abs(data_total_income - data_total_income_mean)

20141.54986471479

<div class="alert alert-info">
<b>Комментарий студента:</b>
<br>
Также будет создан датафрейм data_mean для сравнения значений среднеарифметического и медианных значений столбца total_income в двух датафреймах: data_mean и data_mean, заполнив на этот раз пропущенные значения столбца total_income, в виде среднеарифметического значения.<br>
    <br>А теперь сравним данные, если мы хотим заполнить пропущенные значения средним арифметическим значением датафрейма data_mean.<br>
</div>

In [18]:
data_mean = pd.read_csv('data.csv')
data_mean.head(30)

children  days_employed  dob_years            education  education_id  \
0          1   -8437.673028         42               высшее             0   
1          1   -4024.803754         36              среднее             1   
2          0   -5623.422610         33              Среднее             1   
3          3   -4124.747207         32              среднее             1   
4          0  340266.072047         53              среднее             1   
5          0    -926.185831         27               высшее             0   
6          0   -2879.202052         43               высшее             0   
7          0    -152.779569         50              СРЕДНЕЕ             1   
8          2   -6929.865299         35               ВЫСШЕЕ             0   
9          0   -2188.756445         41              среднее             1   
10         2   -4171.483647         36               высшее             0   
11         0    -792.701887         40              среднее             1   
12         0            NaN         65              среднее             1   
13         0   -1846.641941         54  неоконченное высшее             2   
14         0   -1844.956182         56               высшее             0   
15         1    -972.364419         26              среднее             1   
16         0   -1719.934226         35              среднее             1   
17         0   -2369.999720         33               высшее             0   
18         0  400281.136913         53              среднее             1   
19         0  -10038.818549         48              СРЕДНЕЕ             1   
20         1   -1311.604166         36              среднее             1   
21         1    -253.685166         33              среднее             1   
22         1   -1766.644138         24              среднее             1   
23         0    -272.981385         21               высшее             0   
24         1  338551.952911         57              среднее             1   
25         0  363548.489348         67              среднее             1   
26         0            NaN         41              среднее             1   
27         0    -529.191635         28               высшее             0   
28         1    -717.274324         26               высшее             0   
29         0            NaN         63              среднее             1   

            family_status  family_status_id gender  income_type  debt  \
0         женат / замужем                 0      F    сотрудник     0   
1         женат / замужем                 0      F    сотрудник     0   
2         женат / замужем                 0      M    сотрудник     0   
3         женат / замужем                 0      M    сотрудник     0   
4        гражданский брак                 1      F    пенсионер     0   
5        гражданский брак                 1      M    компаньон     0   
6         женат / замужем                 0      F    компаньон     0   
7         женат / замужем                 0      M    сотрудник     0   
8        гражданский брак                 1      F    сотрудник     0   
9         женат / замужем                 0      M    сотрудник     0   
10        женат / замужем                 0      M    компаньон     0   
11        женат / замужем                 0      F    сотрудник     0   
12       гражданский брак                 1      M    пенсионер     0   
13        женат / замужем                 0      F    сотрудник     0   
14       гражданский брак                 1      F    компаньон     1   
15        женат / замужем                 0      F    сотрудник     0   
16        женат / замужем                 0      F    сотрудник     0   
17       гражданский брак                 1      M    сотрудник     0   
18         вдовец / вдова                 2      F    пенсионер     0   
19              в разводе                 3      F    сотрудник     0   
20        женат / замужем                 0      M    сотрудник     0   
21       г

In [19]:
try:
    data_mean_total_income = pd.to_numeric(data_mean['total_income'].median())
    data_mean_total_income   
except:
    data_mean_total_income = 'В столбце data_total_income могут быть только значения с плавающей точкой и челочисленные значения!'
    data_mean_total_income

In [20]:
data_mean_total_income

145017.93753253992

In [21]:
try:
    data_mean_total_income_mean = pd.to_numeric(data_mean['total_income'].mean())
    data_mean_total_income_mean   
except:
    data_mean_total_income_mean = 'В столбце data_total_income могут быть только значения с плавающей точкой и челочисленные значения!'
    data_mean_total_income_mean

In [22]:
data_mean_total_income_mean

167422.3022081719

In [23]:
data_mean.loc[data_mean['total_income'] != data_mean['total_income'], 'total_income'] = data_mean_total_income_mean  

display(data_mean.head(30))

children  days_employed  dob_years            education  education_id  \
0          1   -8437.673028         42               высшее             0   
1          1   -4024.803754         36              среднее             1   
2          0   -5623.422610         33              Среднее             1   
3          3   -4124.747207         32              среднее             1   
4          0  340266.072047         53              среднее             1   
5          0    -926.185831         27               высшее             0   
6          0   -2879.202052         43               высшее             0   
7          0    -152.779569         50              СРЕДНЕЕ             1   
8          2   -6929.865299         35               ВЫСШЕЕ             0   
9          0   -2188.756445         41              среднее             1   
10         2   -4171.483647         36               высшее             0   
11         0    -792.701887         40              среднее             1   
12         0            NaN         65              среднее             1   
13         0   -1846.641941         54  неоконченное высшее             2   
14         0   -1844.956182         56               высшее             0   
15         1    -972.364419         26              среднее             1   
16         0   -1719.934226         35              среднее             1   
17         0   -2369.999720         33               высшее             0   
18         0  400281.136913         53              среднее             1   
19         0  -10038.818549         48              СРЕДНЕЕ             1   
20         1   -1311.604166         36              среднее             1   
21         1    -253.685166         33              среднее             1   
22         1   -1766.644138         24              среднее             1   
23         0    -272.981385         21               высшее             0   
24         1  338551.952911         57              среднее             1   
25         0  363548.489348         67              среднее             1   
26         0            NaN         41              среднее             1   
27         0    -529.191635         28               высшее             0   
28         1    -717.274324         26               высшее             0   
29         0            NaN         63              среднее             1   

            family_status  family_status_id gender  income_type  debt  \
0         женат / замужем                 0      F    сотрудник     0   
1         женат / замужем                 0      F    сотрудник     0   
2         женат / замужем                 0      M    сотрудник     0   
3         женат / замужем                 0      M    сотрудник     0   
4        гражданский брак                 1      F    пенсионер     0   
5        гражданский брак                 1      M    компаньон     0   
6         женат / замужем                 0      F    компаньон     0   
7         женат / замужем                 0      M    сотрудник     0   
8        гражданский брак                 1      F    сотрудник     0   
9         женат / замужем                 0      M    сотрудник     0   
10        женат / замужем                 0      M    компаньон     0   
11        женат / замужем                 0      F    сотрудник     0   
12       гражданский брак                 1      M    пенсионер     0   
13        женат / замужем                 0      F    сотрудник     0   
14       гражданский брак                 1      F    компаньон     1   
15        женат / замужем                 0      F    сотрудник     0   
16        женат / замужем                 0      F    сотрудник     0   
17       гражданский брак                 1      M    сотрудник     0   
18         вдовец / вдова                 2      F    пенсионер     0   
19              в разводе                 3      F    сотрудник     0   
20        женат / замужем                 0      M    сотрудник     0   
21       г

In [24]:
data_mean_total_income = data_mean['total_income'].median()
data_mean_total_income

156400.3198360834

In [25]:
data_mean_total_income_mean_1 = data_mean['total_income'].mean()
data_mean_total_income_mean_1

167422.30220816366

<div class="alert alert-info">
<b>Комментарий студента:</b> <i>(Ответ на 4-ый вопрос пункта №1, шага №2)</i>
<br>
По двум причинам, по которому лучше заполнить пропуски медианным значением - это:<br>
   <br>1. Если мы выберем серединное значение от общего количества чисел (можем себе позволить, так как число 19351 - это нечётное число, а медианное значение мы можем себе позволить), то медианное значение не изменится до и после заполнения пропусков в столбце total_income. А со заполнением среднего арифмитеского значения такой трюк не получится, потому что изменится не только медианное значение, но и даже само среднее арифмеическое значение столбца total_income (за счёт количества непропущенных значений, до заполнения пропусков, непропущенных значений составляла 19351, а после заполнения уже составляла - 21525 значений).<br>
    <br>2. Ещё одна более практическая причина - это среднее арифметичекое значение находится во второй половине значений медианы, а значит многие клиенты банка пошли с ежемесячными доходами выше среднеарифметических и чуть меньше клиентов с доходами ниже среднеарифметического и, соответственно, не самая большая разница (на 20141.55). А если количество клиентов с доходами выше среднеарифметических в десять раз больше, чем клиентов с доходами ниже среднеарифметического (как в мировозрении Робин Гуда: "Краду деньги у богатых и раздаю бедным"), то лучше для этих целей использовать медианную величину.<br>
</div>

### 0.3 Шаг 2.2 Проверка данных на аномалии и исправления.

In [26]:
display(data.head(30))

children  days_employed  dob_years            education  education_id  \
0          1   -8437.673028         42               высшее             0   
1          1   -4024.803754         36              среднее             1   
2          0   -5623.422610         33              Среднее             1   
3          3   -4124.747207         32              среднее             1   
4          0  340266.072047         53              среднее             1   
5          0    -926.185831         27               высшее             0   
6          0   -2879.202052         43               высшее             0   
7          0    -152.779569         50              СРЕДНЕЕ             1   
8          2   -6929.865299         35               ВЫСШЕЕ             0   
9          0   -2188.756445         41              среднее             1   
10         2   -4171.483647         36               высшее             0   
11         0    -792.701887         40              среднее             1   
12         0            NaN         65              среднее             1   
13         0   -1846.641941         54  неоконченное высшее             2   
14         0   -1844.956182         56               высшее             0   
15         1    -972.364419         26              среднее             1   
16         0   -1719.934226         35              среднее             1   
17         0   -2369.999720         33               высшее             0   
18         0  400281.136913         53              среднее             1   
19         0  -10038.818549         48              СРЕДНЕЕ             1   
20         1   -1311.604166         36              среднее             1   
21         1    -253.685166         33              среднее             1   
22         1   -1766.644138         24              среднее             1   
23         0    -272.981385         21               высшее             0   
24         1  338551.952911         57              среднее             1   
25         0  363548.489348         67              среднее             1   
26         0            NaN         41              среднее             1   
27         0    -529.191635         28               высшее             0   
28         1    -717.274324         26               высшее             0   
29         0            NaN         63              среднее             1   

            family_status  family_status_id gender  income_type  debt  \
0         женат / замужем                 0      F    сотрудник     0   
1         женат / замужем                 0      F    сотрудник     0   
2         женат / замужем                 0      M    сотрудник     0   
3         женат / замужем                 0      M    сотрудник     0   
4        гражданский брак                 1      F    пенсионер     0   
5        гражданский брак                 1      M    компаньон     0   
6         женат / замужем                 0      F    компаньон     0   
7         женат / замужем                 0      M    сотрудник     0   
8        гражданский брак                 1      F    сотрудник     0   
9         женат / замужем                 0      M    сотрудник     0   
10        женат / замужем                 0      M    компаньон     0   
11        женат / замужем                 0      F    сотрудник     0   
12       гражданский брак                 1      M    пенсионер     0   
13        женат / замужем                 0      F    сотрудник     0   
14       гражданский брак                 1      F    компаньон     1   
15        женат / замужем                 0      F    сотрудник     0   
16        женат / замужем                 0      F    сотрудник     0   
17       гражданский брак                 1      M    сотрудник     0   
18         вдовец / вдова                 2      F    пенсионер     0   
19              в разводе                 3      F    сотрудник     0   
20        женат / замужем                 0      M    сотрудник     0   
21       г

<div class="alert alert-info">
<b>Комментарий студента:</b> <i>(Ответ пункта №2, шага №2)</i>
<br>
По двум причинам, по которому лучше заполнить пропуски медианным значением - это:<br>
   <br>В столбце total_income имеются, и пропущенные значения, и подозрительно положительные значения (и чаще всего значения больше 300000), отрицательные значения. Поэтому с подозрительно положительными значения делим на 365 (на среднее количество дней в году, из-за путаницы не "после", а "до" учета дней трудового стажа), с отрицательными значениями - преобразуем в положительные значения, с помощью функции модуля abs(). <br><br> К пропущенными значениям вернёмся позже.<br>
</div>

In [27]:
try:
    data_negative = data[pd.to_numeric(data['days_employed']) < 0]
    data_negative
except:
    data_negative = 'Обнаружены нечисловые значения в столбце data_total_income!'
    data_negative

In [28]:
data_negative

children  days_employed  dob_years       education  education_id  \
0             1   -8437.673028         42          высшее             0   
1             1   -4024.803754         36         среднее             1   
2             0   -5623.422610         33         Среднее             1   
3             3   -4124.747207         32         среднее             1   
5             0    -926.185831         27          высшее             0   
...         ...            ...        ...             ...           ...   
21519         1   -2351.431934         37  ученая степень             4   
21520         1   -4529.316663         43         среднее             1   
21522         1   -2113.346888         38         среднее             1   
21523         3   -3112.481705         38         среднее             1   
21524         2   -1984.507589         40         среднее             1   

          family_status  family_status_id gender income_type  debt  \
0       женат / замужем                 0      F   сотрудник     0   
1       женат / замужем                 0      F   сотрудник     0   
2       женат / замужем                 0      M   сотрудник     0   
3       женат / замужем                 0      M   сотрудник     0   
5      гражданский брак                 1      M   компаньон     0   
...                 ...               ...    ...         ...   ...   
21519         в разводе                 3      M   сотрудник     0   
21520  гражданский брак                 1      F   компаньон     0   
21522  гражданский брак                 1      M   сотрудник     1   
21523   женат / замужем                 0      M   сотрудник     1   
21524   женат / замужем                 0      F   сотрудник     0   

        total_income                            purpose  
0      253875.639453                      покупка жилья  
1      112080.014102            приобретение автомобиля  
2      145885.952297                      покупка жилья  
3      267628.550329         дополнительное образование  
5      255763.565419                      покупка жилья  
...              ...                                ...  
21519  115949.039788  покупка коммерческой недвижимости  
21520  224791.862382                  операции с жильем  
21522   89672.561153                       недвижимость  
21523  244093.050500       на покупку своего автомобиля  
21524   82047.418899              на покупку автомобиля  

[15906 rows x 12 columns]

In [29]:
data_days_employed_negative = abs(data.loc[data['days_employed'] < 0, 'days_employed'])
data_days_employed_negative.head(20)

0      8437.673028
1      4024.803754
2      5623.422610
3      4124.747207
5       926.185831
6      2879.202052
7       152.779569
8      6929.865299
9      2188.756445
10     4171.483647
11      792.701887
13     1846.641941
14     1844.956182
15      972.364419
16     1719.934226
17     2369.999720
19    10038.818549
20     1311.604166
21      253.685166
22     1766.644138
Name: days_employed, dtype: float64

In [30]:
try:
    data_positive = data[pd.to_numeric(data['days_employed']) >= 0]
    data_positive
except:
    data_positive = 'Обнаружены нечисловые значения в столбце data_total_income!'
    data_positive

In [31]:
data_positive

children  days_employed  dob_years education  education_id  \
4             0  340266.072047         53   среднее             1   
18            0  400281.136913         53   среднее             1   
24            1  338551.952911         57   среднее             1   
25            0  363548.489348         67   среднее             1   
30            1  335581.668515         62   среднее             1   
...         ...            ...        ...       ...           ...   
21505         0  338904.866406         53   среднее             1   
21508         0  386497.714078         62   среднее             1   
21509         0  362161.054124         59    высшее             0   
21518         0  373995.710838         59   СРЕДНЕЕ             1   
21521         0  343937.404131         67   среднее             1   

               family_status  family_status_id gender income_type  debt  \
4           гражданский брак                 1      F   пенсионер     0   
18            вдовец / вдова                 2      F   пенсионер     0   
24     Не женат / не замужем                 4      F   пенсионер     0   
25           женат / замужем                 0      M   пенсионер     0   
30           женат / замужем                 0      F   пенсионер     0   
...                      ...               ...    ...         ...   ...   
21505       гражданский брак                 1      M   пенсионер     0   
21508        женат / замужем                 0      M   пенсионер     0   
21509        женат / замужем                 0      M   пенсионер     0   
21518        женат / замужем                 0      F   пенсионер     0   
21521        женат / замужем                 0      F   пенсионер     0   

        total_income                                purpose  
4      158616.077870                        сыграть свадьбу  
18      56823.777243     на покупку подержанного автомобиля  
24     290547.235997  операции с коммерческой недвижимостью  
25      55112.757732                   покупка недвижимости  
30     171456.067993  операции с коммерческой недвижимостью  
...              ...                                    ...  
21505   75439.993167                        сыграть свадьбу  
21508   72638.590915                           недвижимость  
21509   73029.059379               операции с недвижимостью  
21518  153864.650328                   сделка с автомобилем  
21521  155999.806512                   сделка с автомобилем  

[3445 rows x 12 columns]

In [32]:
data_days_employed_positive = data.loc[data['days_employed'] >= 0, 'days_employed'] / 365
data_days_employed_positive.head(20)

4       932.235814
18     1096.660649
24      927.539597
25      996.023258
30      919.401832
35     1079.509787
50      969.127212
56     1014.096129
71      926.338438
78      985.542315
86     1051.872739
87      925.094616
88     1022.273396
98      999.743029
99      949.429093
101    1072.764279
104    1003.626437
119    1047.093504
128    1038.454577
129     989.069374
Name: days_employed, dtype: float64

In [33]:
data.loc[data['days_employed'] < 0, 'days_employed'] = abs(data['days_employed']) * 365 
data.loc[data['days_employed'] >= 0, 'days_employed'] = data['days_employed'] / 365

display(data.head(30))

children  days_employed  dob_years            education  education_id  \
0          1    8437.673028         42               высшее             0   
1          1    4024.803754         36              среднее             1   
2          0    5623.422610         33              Среднее             1   
3          3    4124.747207         32              среднее             1   
4          0     932.235814         53              среднее             1   
5          0     926.185831         27               высшее             0   
6          0    2879.202052         43               высшее             0   
7          0     152.779569         50              СРЕДНЕЕ             1   
8          2    6929.865299         35               ВЫСШЕЕ             0   
9          0    2188.756445         41              среднее             1   
10         2    4171.483647         36               высшее             0   
11         0     792.701887         40              среднее             1   
12         0            NaN         65              среднее             1   
13         0    1846.641941         54  неоконченное высшее             2   
14         0    1844.956182         56               высшее             0   
15         1     972.364419         26              среднее             1   
16         0    1719.934226         35              среднее             1   
17         0    2369.999720         33               высшее             0   
18         0    1096.660649         53              среднее             1   
19         0   10038.818549         48              СРЕДНЕЕ             1   
20         1    1311.604166         36              среднее             1   
21         1     253.685166         33              среднее             1   
22         1    1766.644138         24              среднее             1   
23         0     272.981385         21               высшее             0   
24         1     927.539597         57              среднее             1   
25         0     996.023258         67              среднее             1   
26         0            NaN         41              среднее             1   
27         0     529.191635         28               высшее             0   
28         1     717.274324         26               высшее             0   
29         0            NaN         63              среднее             1   

            family_status  family_status_id gender  income_type  debt  \
0         женат / замужем                 0      F    сотрудник     0   
1         женат / замужем                 0      F    сотрудник     0   
2         женат / замужем                 0      M    сотрудник     0   
3         женат / замужем                 0      M    сотрудник     0   
4        гражданский брак                 1      F    пенсионер     0   
5        гражданский брак                 1      M    компаньон     0   
6         женат / замужем                 0      F    компаньон     0   
7         женат / замужем                 0      M    сотрудник     0   
8        гражданский брак                 1      F    сотрудник     0   
9         женат / замужем                 0      M    сотрудник     0   
10        женат / замужем                 0      M    компаньон     0   
11        женат / замужем                 0      F    сотрудник     0   
12       гражданский брак                 1      M    пенсионер     0   
13        женат / замужем                 0      F    сотрудник     0   
14       гражданский брак                 1      F    компаньон     1   
15        женат / замужем                 0      F    сотрудник     0   
16        женат / замужем                 0      F    сотрудник     0   
17       гражданский брак                 1      M    сотрудник     0   
18         вдовец / вдова                 2      F    пенсионер     0   
19              в разводе                 3      F    сотрудник     0   
20        женат / замужем                 0      M    сотрудник     0   
21       г

In [34]:
data_days_employed_median = data['days_employed'].median()
data_days_employed_median

1203.369528770489

<div class="alert alert-info">
<b>Комментарий студента:</b> <i>(Ответ пункта №2, шага №2)</i>
<br>Не только в столбце days_employed обнаруживаются подобного рода аномалии, но и в столбце children (количество детей) могут содержать отрицательные значения, а значение children может содержать только положительные целочисленные (натуральные) значения и число 0 (отсутствие детей).<br>        
<br>Обнаружить и исправить эту аномалию помогут действия с помощью функция с параметрами query(), abs() (для исправления количества детей из значения -1 в 1), а также с помощью функции .astype('int') для преобразования целочисленного значения из строковых значений, которые могут только прикидываться целочисленными значениями.<br>
</div>

In [35]:
data['children'].unique()

array([ 1,  0,  3,  2, -1,  4, 20,  5], dtype=int64)

In [36]:
data.query('children < 0')

children  days_employed  dob_years            education  education_id  \
291          -1    4417.703588         46              среднее             1   
705          -1     902.084528         50              среднее             1   
742          -1    3174.456205         57              среднее             1   
800          -1     958.870828         54              среднее             1   
941          -1            NaN         57              Среднее             1   
1363         -1    1195.264956         55              СРЕДНЕЕ             1   
1929         -1    1461.303336         38              среднее             1   
2073         -1    2539.761232         42              среднее             1   
3814         -1    3045.290443         26              Среднее             1   
4201         -1     901.101738         41              среднее             1   
4402         -1    1090.414528         64              СРЕДНЕЕ             1   
4542         -1    1811.899756         32              среднее             1   
5272         -1    1143.485347         46              среднее             1   
6013         -1    1361.258696         46               высшее             0   
6385         -1    1014.288976         48              среднее             1   
7190         -1    5928.202068         34              СРЕДНЕЕ             1   
7278         -1     526.318451         51              среднее             1   
7615         -1            NaN         35              среднее             1   
7685         -1    3237.360455         53              среднее             1   
8229         -1    1803.441074         54               высшее             0   
8251         -1    3113.998449         31              среднее             1   
8561         -1     195.479496         31              среднее             1   
9565         -1    2896.629686         34               высшее             0   
9574         -1    2710.419901         28               высшее             0   
10177        -1    1743.604011         37              среднее             1   
10365        -1     947.326372         63               ВЫСШЕЕ             0   
10918        -1     932.874080         50              среднее             1   
11109        -1    3438.463024         59              среднее             1   
11268        -1    1048.782203         30               высшее             0   
11617        -1     370.827130         27              среднее             1   
12304        -1    8493.101252         61  неоконченное высшее             2   
13786        -1            NaN         42              среднее             1   
14357        -1     268.337037         23              среднее             1   
15147        -1    9851.184337         44              среднее             1   
15435        -1    3614.220232         40               высшее             0   
16129        -1     457.861760         33              среднее             1   
16265        -1    2802.218127         40               высшее             0   
17095        -1    2809.693200         34              среднее             1   
17429        -1     895.379738         37              среднее             1   
17657        -1    4571.957475         41              среднее             1   
18219        -1    3575.215641         33              среднее             1   
19100        -1     617.246968         38              среднее             1   
19366        -1     372.034749         43              СРЕДНЕЕ             1   
19417        -1     959.837699         28              среднее             1   
20393        -1     973.033170         69              среднее             1   
20717        -1     661.822321         32               высшее             0   
21140        -1    1422.668059         44              среднее             1   

               family_status  family_status_id gender  income_type  debt  \
291         гражданский брак                 1      F    сотрудник     0   
705          ж

<div class="alert alert-info">
<b>Комментарий студента:</b> <i>(Ответ пункта №2, шага №2)</i>
<br>Чтобы у клиента банка было двадцать (!) детей - это уникальный случай, который мог бы войти в книгу рекордов Гиннеса. Поэтому количество детей сократим до двух, что соответствует действительности.<br></div>

In [37]:
data.query('children == 20')

children  days_employed  dob_years education  education_id  \
606          20     880.221113         21   среднее             1   
720          20     855.595512         44   среднее             1   
1074         20    3310.411598         56   среднее             1   
2510         20    2714.161249         59    высшее             0   
2941         20    2161.591519          0   среднее             1   
...         ...            ...        ...       ...           ...   
21008        20    1240.257910         40   среднее             1   
21325        20     601.174883         37   среднее             1   
21390        20            NaN         53   среднее             1   
21404        20     494.788448         52   среднее             1   
21491        20     173.954460         27   среднее             1   

         family_status  family_status_id gender income_type  debt  \
606    женат / замужем                 0      M   компаньон     0   
720    женат / замужем                 0      F   компаньон     0   
1074   женат / замужем                 0      F   сотрудник     1   
2510    вдовец / вдова                 2      F   сотрудник     0   
2941   женат / замужем                 0      F   сотрудник     0   
...                ...               ...    ...         ...   ...   
21008  женат / замужем                 0      F   сотрудник     1   
21325  женат / замужем                 0      F   компаньон     0   
21390  женат / замужем                 0      M   компаньон     0   
21404  женат / замужем                 0      M   компаньон     0   
21491  женат / замужем                 0      F   сотрудник     0   

        total_income                                purpose  
606    145334.865002                          покупка жилья  
720    112998.738649                   покупка недвижимости  
1074   229518.537004                  получение образования  
2510   264474.835577  операции с коммерческой недвижимостью  
2941   199739.941398                  на покупку автомобиля  
...              ...                                    ...  
21008  133524.010303                        свой автомобиль  
21325  102986.065978                 профильное образование  
21390  145017.937533             покупка жилой недвижимости  
21404  156629.683642        операции со своей недвижимостью  
21491  155520.899688     на покупку подержанного автомобиля  

[76 rows x 12 columns]

In [38]:
#data.loc[data['children'] == 20, 'children'] = (data['children'] / 10).astype('int')
#data.loc[data['children'] < 0, 'children'] = abs(data['children']).astype('int')
        
try:
    data.loc[data['children'] == 20, 'children'] = abs(data['children'] / 10).astype('int')  
    data.loc[data['children'] < 0, 'children'] = abs(data['children']).astype('int')  
except:
    data.loc[data['children'], 'children'] = 0

display(data.head(291))

children  days_employed  dob_years education  education_id  \
0           1    8437.673028         42    высшее             0   
1           1    4024.803754         36   среднее             1   
2           0    5623.422610         33   Среднее             1   
3           3    4124.747207         32   среднее             1   
4           0     932.235814         53   среднее             1   
..        ...            ...        ...       ...           ...   
286         0    9854.773564         45   среднее             1   
287         0    1382.864823         47   среднее             1   
288         0    1303.957795         28   среднее             1   
289         1     710.680916         44   среднее             1   
290         0    1006.240054         35   среднее             1   

        family_status  family_status_id gender income_type  debt  \
0     женат / замужем                 0      F   сотрудник     0   
1     женат / замужем                 0      F   сотрудник     0   
2     женат / замужем                 0      M   сотрудник     0   
3     женат / замужем                 0      M   сотрудник     0   
4    гражданский брак                 1      F   пенсионер     0   
..                ...               ...    ...         ...   ...   
286   женат / замужем                 0      F   сотрудник     0   
287   женат / замужем                 0      M   сотрудник     1   
288   женат / замужем                 0      F   сотрудник     0   
289   женат / замужем                 0      F   сотрудник     0   
290   женат / замужем                 0      M   компаньон     0   

      total_income                                 purpose  
0    253875.639453                           покупка жилья  
1    112080.014102                 приобретение автомобиля  
2    145885.952297                           покупка жилья  
3    267628.550329              дополнительное образование  
4    158616.077870                         сыграть свадьбу  
..             ...                                     ...  
286  104614.115527      на покупку подержанного автомобиля  
287  143042.614306                    покупка своего жилья  
288   86117.270687  строительство собственной недвижимости  
289  153439.596825                            ремонт жилью  
290  160483.242490   получение дополнительного образования  

[291 rows x 12 columns]

<div class="alert alert-info">
<b>Комментарий студента:</b> <i>(Ответ пункта №2, шага №2)</i>
<br>В столбце days_employed пропущенные значения заполняем медианным значением способом, которое было описано в шаге 2.1 "Заполнение пропусков". 
<br>        
</div>

In [39]:
data['days_employed'] = data['days_employed'].fillna(data_days_employed_median)

display(data.head(30))

children  days_employed  dob_years            education  education_id  \
0          1    8437.673028         42               высшее             0   
1          1    4024.803754         36              среднее             1   
2          0    5623.422610         33              Среднее             1   
3          3    4124.747207         32              среднее             1   
4          0     932.235814         53              среднее             1   
5          0     926.185831         27               высшее             0   
6          0    2879.202052         43               высшее             0   
7          0     152.779569         50              СРЕДНЕЕ             1   
8          2    6929.865299         35               ВЫСШЕЕ             0   
9          0    2188.756445         41              среднее             1   
10         2    4171.483647         36               высшее             0   
11         0     792.701887         40              среднее             1   
12         0    1203.369529         65              среднее             1   
13         0    1846.641941         54  неоконченное высшее             2   
14         0    1844.956182         56               высшее             0   
15         1     972.364419         26              среднее             1   
16         0    1719.934226         35              среднее             1   
17         0    2369.999720         33               высшее             0   
18         0    1096.660649         53              среднее             1   
19         0   10038.818549         48              СРЕДНЕЕ             1   
20         1    1311.604166         36              среднее             1   
21         1     253.685166         33              среднее             1   
22         1    1766.644138         24              среднее             1   
23         0     272.981385         21               высшее             0   
24         1     927.539597         57              среднее             1   
25         0     996.023258         67              среднее             1   
26         0    1203.369529         41              среднее             1   
27         0     529.191635         28               высшее             0   
28         1     717.274324         26               высшее             0   
29         0    1203.369529         63              среднее             1   

            family_status  family_status_id gender  income_type  debt  \
0         женат / замужем                 0      F    сотрудник     0   
1         женат / замужем                 0      F    сотрудник     0   
2         женат / замужем                 0      M    сотрудник     0   
3         женат / замужем                 0      M    сотрудник     0   
4        гражданский брак                 1      F    пенсионер     0   
5        гражданский брак                 1      M    компаньон     0   
6         женат / замужем                 0      F    компаньон     0   
7         женат / замужем                 0      M    сотрудник     0   
8        гражданский брак                 1      F    сотрудник     0   
9         женат / замужем                 0      M    сотрудник     0   
10        женат / замужем                 0      M    компаньон     0   
11        женат / замужем                 0      F    сотрудник     0   
12       гражданский брак                 1      M    пенсионер     0   
13        женат / замужем                 0      F    сотрудник     0   
14       гражданский брак                 1      F    компаньон     1   
15        женат / замужем                 0      F    сотрудник     0   
16        женат / замужем                 0      F    сотрудник     0   
17       гражданский брак                 1      M    сотрудник     0   
18         вдовец / вдова                 2      F    пенсионер     0   
19              в разводе                 3      F    сотрудник     0   
20        женат / замужем                 0      M    сотрудник     0   
21       г

<div class="alert alert-info">
<b>Комментарий студента:</b> <i>(Ответ на вопрос пункта №2, шага №2)</i>
<br>Судя, по значениям-аномалиям из столбца days_employed, если значение меньше нуля (что в принципе быть не может), то все значения возводится по модулю, с помощью метода abs(), и так, как этот столбец обозначает количество дней трудового стажа.
<br>Но в случае с положительными значениями трудового стажа столбца days_employed нужно разделить все положительные значения на значение дней в обычном году 365 (обработка данных перепутала значения в дней трудового стажа вместо "после обработки" в "до обработки"), потому что ни один человек, не то, что не сможет работать, но и жить (например) 932 лет! Так что, эти значения могут представлять за собой - не как дни трудового стажа, а как часы трудового стажа, разделив полученные значения на 24.  
<br>        
</div>

### 0.4 Шаг 2.3. Изменение типов данных.

<div class="alert alert-info">
<b>Комментарий студента:</b> <i>(Ответ на вопрос шага №3)</i>
<br> 
    С помощью метода astype() преобразуем значения из столбца 'total_income' в целочисленный тип данных int. 
<br>        
</div>

In [40]:
data['total_income'] = data['total_income'].astype('int')
display(data.head(20))

children  days_employed  dob_years            education  education_id  \
0          1    8437.673028         42               высшее             0   
1          1    4024.803754         36              среднее             1   
2          0    5623.422610         33              Среднее             1   
3          3    4124.747207         32              среднее             1   
4          0     932.235814         53              среднее             1   
5          0     926.185831         27               высшее             0   
6          0    2879.202052         43               высшее             0   
7          0     152.779569         50              СРЕДНЕЕ             1   
8          2    6929.865299         35               ВЫСШЕЕ             0   
9          0    2188.756445         41              среднее             1   
10         2    4171.483647         36               высшее             0   
11         0     792.701887         40              среднее             1   
12         0    1203.369529         65              среднее             1   
13         0    1846.641941         54  неоконченное высшее             2   
14         0    1844.956182         56               высшее             0   
15         1     972.364419         26              среднее             1   
16         0    1719.934226         35              среднее             1   
17         0    2369.999720         33               высшее             0   
18         0    1096.660649         53              среднее             1   
19         0   10038.818549         48              СРЕДНЕЕ             1   

       family_status  family_status_id gender income_type  debt  total_income  \
0    женат / замужем                 0      F   сотрудник     0        253875   
1    женат / замужем                 0      F   сотрудник     0        112080   
2    женат / замужем                 0      M   сотрудник     0        145885   
3    женат / замужем                 0      M   сотрудник     0        267628   
4   гражданский брак                 1      F   пенсионер     0        158616   
5   гражданский брак                 1      M   компаньон     0        255763   
6    женат / замужем                 0      F   компаньон     0        240525   
7    женат / замужем                 0      M   сотрудник     0        135823   
8   гражданский брак                 1      F   сотрудник     0         95856   
9    женат / замужем                 0      M   сотрудник     0        144425   
10   женат / замужем                 0      M   компаньон     0        113943   
11   женат / замужем                 0      F   сотрудник     0         77069   
12  гражданский брак                 1      M   пенсионер     0        145017   
13   женат / замужем                 0      F   сотрудник     0        130458   
14  гражданский брак                 1      F   компаньон     1        165127   
15   женат / замужем                 0      F   сотрудник     0        116820   
16   женат / замужем                 0      F   сотрудник     0        289202   
17  гражданский брак                 1      M   сотрудник     0         90410   
18    вдовец / вдова                 2      F   пенсионер     0         56823   
19         в разводе                 3      F   сотрудник     0        242831   

                                   purpose  
0                            покупка жилья  
1                  приобретение автомобиля  
2                            покупка жилья  
3               дополнительное образование  
4                          сыграть свадьбу  
5                            покупка жилья  
6                        операции с жильем  
7                              образование  
8                    на проведение свадьбы  
9                  покупка жилья для семьи  
10                    покупка недвижимости  
11       покупка коммерческой недвижимости  
12                         сыграть свадьбу  
13                 приобретение автомобиля  
14       

### 0.5 Шаг 2.4. Удаление дубликатов.

<div class="alert alert-info">
<b>Комментарий студента:</b>
<br> 
    Для начала, чтобы удалить дубликаты с датафрейма data, нужно для начала определить количество строк до удаления и после удаления явных и неявных дубликатов, спомощью метода .shape[0], присвоив переменными data_to и data_after, а в конце определим разницу с помощью разность между переменными data_after и data_to.  
<br>        
</div>

In [41]:
data_to = data.shape[0]
data_to

21525

In [42]:
data[data.duplicated()] #Поиск дубликатов

children  days_employed  dob_years education  education_id  \
2849          0    1203.369529         41   среднее             1   
4182          1    1203.369529         34    ВЫСШЕЕ             0   
4851          0    1203.369529         60   среднее             1   
5557          0    1203.369529         58   среднее             1   
7808          0    1203.369529         57   среднее             1   
8583          0    1203.369529         58    высшее             0   
9238          2    1203.369529         34   среднее             1   
9528          0    1203.369529         66   среднее             1   
9627          0    1203.369529         56   среднее             1   
10462         0    1203.369529         62   среднее             1   
10697         0    1203.369529         40   среднее             1   
10864         0    1203.369529         62   среднее             1   
10994         0    1203.369529         62   среднее             1   
11791         0    1203.369529         47   среднее             1   
12373         0    1203.369529         58   среднее             1   
12375         1    1203.369529         37   среднее             1   
12736         0    1203.369529         59   среднее             1   
13025         1    1203.369529         44   среднее             1   
13639         0    1203.369529         64   среднее             1   
13773         0    1203.369529         35   среднее             1   
13878         1    1203.369529         31   среднее             1   
13942         0    1203.369529         44   среднее             1   
14432         2    1203.369529         36    высшее             0   
14832         0    1203.369529         50   среднее             1   
15091         0    1203.369529         58   среднее             1   
15188         0    1203.369529         60   среднее             1   
15273         0    1203.369529         57   среднее             1   
16176         0    1203.369529         47   среднее             1   
16378         0    1203.369529         46   среднее             1   
16902         2    1203.369529         39   среднее             1   
16904         1    1203.369529         32    высшее             0   
17379         0    1203.369529         54    высшее             0   
17755         1    1203.369529         43   среднее             1   
17774         1    1203.369529         40   среднее             1   
18328         0    1203.369529         29    высшее             0   
18349         1    1203.369529         30    высшее             0   
18428         0    1203.369529         64   среднее             1   
18521         0    1203.369529         56   среднее             1   
18563         0    1203.369529         54   среднее             1   
18755         0    1203.369529         58   среднее             1   
19041         0    1203.369529         56   среднее             1   
19184         0    1203.369529         46   среднее             1   
19321         0    1203.369529         23   среднее             1   
19387         0    1203.369529         38    высшее             0   
19688         0    1203.369529         61   среднее             1   
19832         0    1203.369529         48   среднее             1   
19946         0    1203.369529         57   среднее             1   
20116         0    1203.369529         57   среднее             1   
20165         0    1203.369529         42   среднее             1   
20702         0    1203.369529         64   среднее             1   
21032         0    1203.369529         60   среднее             1   
21132         0    1203.369529         47   среднее             1   
21281         1    1203.369529         30    высшее             0   
21415         0    1203.369529         54   среднее             1   

               family_status  family_status_id gender  income_type  debt  \
2849         женат / замужем                 0      F    сотрудник     0   
4182        гражданский брак                 1      F    со

In [43]:
data.duplicated().sum() #Сумма дубликатов

54

In [44]:
data = data.drop_duplicates().reset_index(drop=True)
display(data.head(30))

children  days_employed  dob_years            education  education_id  \
0          1    8437.673028         42               высшее             0   
1          1    4024.803754         36              среднее             1   
2          0    5623.422610         33              Среднее             1   
3          3    4124.747207         32              среднее             1   
4          0     932.235814         53              среднее             1   
5          0     926.185831         27               высшее             0   
6          0    2879.202052         43               высшее             0   
7          0     152.779569         50              СРЕДНЕЕ             1   
8          2    6929.865299         35               ВЫСШЕЕ             0   
9          0    2188.756445         41              среднее             1   
10         2    4171.483647         36               высшее             0   
11         0     792.701887         40              среднее             1   
12         0    1203.369529         65              среднее             1   
13         0    1846.641941         54  неоконченное высшее             2   
14         0    1844.956182         56               высшее             0   
15         1     972.364419         26              среднее             1   
16         0    1719.934226         35              среднее             1   
17         0    2369.999720         33               высшее             0   
18         0    1096.660649         53              среднее             1   
19         0   10038.818549         48              СРЕДНЕЕ             1   
20         1    1311.604166         36              среднее             1   
21         1     253.685166         33              среднее             1   
22         1    1766.644138         24              среднее             1   
23         0     272.981385         21               высшее             0   
24         1     927.539597         57              среднее             1   
25         0     996.023258         67              среднее             1   
26         0    1203.369529         41              среднее             1   
27         0     529.191635         28               высшее             0   
28         1     717.274324         26               высшее             0   
29         0    1203.369529         63              среднее             1   

            family_status  family_status_id gender  income_type  debt  \
0         женат / замужем                 0      F    сотрудник     0   
1         женат / замужем                 0      F    сотрудник     0   
2         женат / замужем                 0      M    сотрудник     0   
3         женат / замужем                 0      M    сотрудник     0   
4        гражданский брак                 1      F    пенсионер     0   
5        гражданский брак                 1      M    компаньон     0   
6         женат / замужем                 0      F    компаньон     0   
7         женат / замужем                 0      M    сотрудник     0   
8        гражданский брак                 1      F    сотрудник     0   
9         женат / замужем                 0      M    сотрудник     0   
10        женат / замужем                 0      M    компаньон     0   
11        женат / замужем                 0      F    сотрудник     0   
12       гражданский брак                 1      M    пенсионер     0   
13        женат / замужем                 0      F    сотрудник     0   
14       гражданский брак                 1      F    компаньон     1   
15        женат / замужем                 0      F    сотрудник     0   
16        женат / замужем                 0      F    сотрудник     0   
17       гражданский брак                 1      M    сотрудник     0   
18         вдовец / вдова                 2      F    пенсионер     0   
19              в разводе                 3      F    сотрудник     0   
20        женат / замужем                 0      M    сотрудник     0   
21       г

<div class="alert alert-info">
<b>Комментарий студента:</b>
<br>1. С помощью метода мы снова определяем количество строк, с помощью метода .shape[0].
<br>2. С помощью функции .duplicated(), к которому прикреплена переменная хранения датафрейма data и заключённая квадратными скобками к такой же переменной мы сможем получить таблицу с дубликатами и обнаруживаем интересную вещь: дубликатами являются те строки, где столбцы days_employed и total_income изначально были пустыми значенями (см. шаг 2.1 Заполнение пропусков).
<br>3. При использовании двух функций: .duplicated().sum() подсчитали количество строк-дубликатов.
<br>4. А при использовании функции .drop_duplicates().reset_index(drop=True), датафрейм избавился от явных дубликатов.<br>
<br>А вот с неявными дубликатами (из-за столбцов education и family_status) всё не так однозначно. Но об этом, всё по порядку.<br>   
</div>

In [45]:
try:
    data['education'] = data['education'].str.lower()
    data['family_status'] = data['family_status'].str.lower()
except:
    data['education'] = 'Обнаружены строковые значения в столбцах education, которые нельзя заменить на численные значения с плавающей точкой!'
    data['family_status'] = 'Обнаружены строковые значения в столбцах family_status, которые нельзя заменить на численные значения с плавающей точкой!'
display(data.head(30))

children  days_employed  dob_years            education  education_id  \
0          1    8437.673028         42               высшее             0   
1          1    4024.803754         36              среднее             1   
2          0    5623.422610         33              среднее             1   
3          3    4124.747207         32              среднее             1   
4          0     932.235814         53              среднее             1   
5          0     926.185831         27               высшее             0   
6          0    2879.202052         43               высшее             0   
7          0     152.779569         50              среднее             1   
8          2    6929.865299         35               высшее             0   
9          0    2188.756445         41              среднее             1   
10         2    4171.483647         36               высшее             0   
11         0     792.701887         40              среднее             1   
12         0    1203.369529         65              среднее             1   
13         0    1846.641941         54  неоконченное высшее             2   
14         0    1844.956182         56               высшее             0   
15         1     972.364419         26              среднее             1   
16         0    1719.934226         35              среднее             1   
17         0    2369.999720         33               высшее             0   
18         0    1096.660649         53              среднее             1   
19         0   10038.818549         48              среднее             1   
20         1    1311.604166         36              среднее             1   
21         1     253.685166         33              среднее             1   
22         1    1766.644138         24              среднее             1   
23         0     272.981385         21               высшее             0   
24         1     927.539597         57              среднее             1   
25         0     996.023258         67              среднее             1   
26         0    1203.369529         41              среднее             1   
27         0     529.191635         28               высшее             0   
28         1     717.274324         26               высшее             0   
29         0    1203.369529         63              среднее             1   

            family_status  family_status_id gender  income_type  debt  \
0         женат / замужем                 0      F    сотрудник     0   
1         женат / замужем                 0      F    сотрудник     0   
2         женат / замужем                 0      M    сотрудник     0   
3         женат / замужем                 0      M    сотрудник     0   
4        гражданский брак                 1      F    пенсионер     0   
5        гражданский брак                 1      M    компаньон     0   
6         женат / замужем                 0      F    компаньон     0   
7         женат / замужем                 0      M    сотрудник     0   
8        гражданский брак                 1      F    сотрудник     0   
9         женат / замужем                 0      M    сотрудник     0   
10        женат / замужем                 0      M    компаньон     0   
11        женат / замужем                 0      F    сотрудник     0   
12       гражданский брак                 1      M    пенсионер     0   
13        женат / замужем                 0      F    сотрудник     0   
14       гражданский брак                 1      F    компаньон     1   
15        женат / замужем                 0      F    сотрудник     0   
16        женат / замужем                 0      F    сотрудник     0   
17       гражданский брак                 1      M    сотрудник     0   
18         вдовец / вдова                 2      F    пенсионер     0   
19              в разводе                 3      F    сотрудник     0   
20        женат / замужем                 0      M    сотрудник     0   
21       г

In [46]:
data.shape[0]

21471

In [47]:
data.duplicated().sum() 

17

In [48]:
data = data.drop_duplicates().reset_index(drop=True)
display(data.head(30))

children  days_employed  dob_years            education  education_id  \
0          1    8437.673028         42               высшее             0   
1          1    4024.803754         36              среднее             1   
2          0    5623.422610         33              среднее             1   
3          3    4124.747207         32              среднее             1   
4          0     932.235814         53              среднее             1   
5          0     926.185831         27               высшее             0   
6          0    2879.202052         43               высшее             0   
7          0     152.779569         50              среднее             1   
8          2    6929.865299         35               высшее             0   
9          0    2188.756445         41              среднее             1   
10         2    4171.483647         36               высшее             0   
11         0     792.701887         40              среднее             1   
12         0    1203.369529         65              среднее             1   
13         0    1846.641941         54  неоконченное высшее             2   
14         0    1844.956182         56               высшее             0   
15         1     972.364419         26              среднее             1   
16         0    1719.934226         35              среднее             1   
17         0    2369.999720         33               высшее             0   
18         0    1096.660649         53              среднее             1   
19         0   10038.818549         48              среднее             1   
20         1    1311.604166         36              среднее             1   
21         1     253.685166         33              среднее             1   
22         1    1766.644138         24              среднее             1   
23         0     272.981385         21               высшее             0   
24         1     927.539597         57              среднее             1   
25         0     996.023258         67              среднее             1   
26         0    1203.369529         41              среднее             1   
27         0     529.191635         28               высшее             0   
28         1     717.274324         26               высшее             0   
29         0    1203.369529         63              среднее             1   

            family_status  family_status_id gender  income_type  debt  \
0         женат / замужем                 0      F    сотрудник     0   
1         женат / замужем                 0      F    сотрудник     0   
2         женат / замужем                 0      M    сотрудник     0   
3         женат / замужем                 0      M    сотрудник     0   
4        гражданский брак                 1      F    пенсионер     0   
5        гражданский брак                 1      M    компаньон     0   
6         женат / замужем                 0      F    компаньон     0   
7         женат / замужем                 0      M    сотрудник     0   
8        гражданский брак                 1      F    сотрудник     0   
9         женат / замужем                 0      M    сотрудник     0   
10        женат / замужем                 0      M    компаньон     0   
11        женат / замужем                 0      F    сотрудник     0   
12       гражданский брак                 1      M    пенсионер     0   
13        женат / замужем                 0      F    сотрудник     0   
14       гражданский брак                 1      F    компаньон     1   
15        женат / замужем                 0      F    сотрудник     0   
16        женат / замужем                 0      F    сотрудник     0   
17       гражданский брак                 1      M    сотрудник     0   
18         вдовец / вдова                 2      F    пенсионер     0   
19              в разводе                 3      F    сотрудник     0   
20        женат / замужем                 0      M    сотрудник     0   
21       г

In [49]:
data_after = data.shape[0]
data_after

21454

In [50]:
data_to - data_after

71

<div class="alert alert-info">
<b>Комментарий студента:</b>
<br>Алгоритм для утранения неявных дубликатов следующий:<br>
    <br>1. Один из главных инструментов для выявления неявных дубликатов является метод .str.lower().
    <br>2. После выполнения простой манипуляции по замене заглавных букв в прописные столбцов 'family_status' выполняем действия, которые описаны в предыдущем комментарии по удалению уже новых явных дубликатов, которые были созданны, с помощью метода .drop_duplicates().reset_index(drop=True) (с новой индексацией, с удалением старой). 
    <br>3. С помощью метода мы снова определяем количество строк, с помощью метода .shape[0], через переменную data_after.
    <br>4. Определим разность между переменными переменными data_after и data_to.
<br>
</div>

<div class="alert alert-info">
<b>Комментарий студента:</b><i>(Вывод шага №4)</i>
<br>Общее количество явных и неявных дубликатов составляет 71 строка - не такой и плохой результат, но терять бдительности при обнаружении дубликатов не стоит.<br>
<br>Часто возможными причинами появления дубликатов являются:
<br>1. Переотправка заявки для получения кредита, т.е. уточнение цели получения кредита (строка purpose) (люди часто ошибаются).
<br>2. Люди часто неуверенны, когда они заполняли данные для получения кредита и не редко забывают о факте того, что они все ли правильно заполнили данные или нет.   

<br>
</div>

### 0.6 Шаг 2.5. Формирование дополнительных датафреймов словарей, декомпозиция исходного датафрейма.

<div class="alert alert-info">
<b>Комментарий студента:</b>
<br>Создаём датафрейм с столбцами: 'education', 'education_id', для связи между нормальным значением уровнем образования и зашифрованной цифрой, указывающей на этот уровень образования. Также и со столбцами: 'family_status', 'family_status_id', который указывает положение в семье и также зашифрованной цифрой. А сначала выведем все уникальные значения из всех указанных выше столбцов.<br>  
</div>

In [51]:
data['education'].unique()

array(['высшее', 'среднее', 'неоконченное высшее', 'начальное',
       'ученая степень'], dtype=object)

In [52]:
data['education_id'].unique()

array([0, 1, 2, 3, 4], dtype=int64)

In [53]:
data['family_status'].unique()

array(['женат / замужем', 'гражданский брак', 'вдовец / вдова',
       'в разводе', 'не женат / не замужем'], dtype=object)

In [54]:
data['family_status_id'].unique()

array([0, 1, 2, 3, 4], dtype=int64)

<div class="alert alert-info">
<b>Комментарий студента:</b>
<br>Затем создадим два датафрейма part_education и part_family_status для того, чтобы сравнить полные значения уровня образования и статус семейного положения с зашифрованными цифрами. Выводим 15 первых и последних значений уже созданных датафреймов part_education и part_family_status.<br>  
</div>

In [55]:
part_education = data[['education', 'education_id']]
display(part_education.head(15))
display(part_education.tail(15))

education  education_id
0                высшее             0
1               среднее             1
2               среднее             1
3               среднее             1
4               среднее             1
5                высшее             0
6                высшее             0
7               среднее             1
8                высшее             0
9               среднее             1
10               высшее             0
11              среднее             1
12              среднее             1
13  неоконченное высшее             2
14               высшее             0

education  education_id
21439              среднее             1
21440               высшее             0
21441               высшее             0
21442              среднее             1
21443  неоконченное высшее             2
21444              среднее             1
21445               высшее             0
21446               высшее             0
21447              среднее             1
21448       ученая степень             4
21449              среднее             1
21450              среднее             1
21451              среднее             1
21452              среднее             1
21453              среднее             1

In [56]:
part_family_status = data[['family_status', 'family_status_id']]
display(part_family_status.head(15))
display(part_family_status.tail(15))

family_status  family_status_id
0    женат / замужем                 0
1    женат / замужем                 0
2    женат / замужем                 0
3    женат / замужем                 0
4   гражданский брак                 1
5   гражданский брак                 1
6    женат / замужем                 0
7    женат / замужем                 0
8   гражданский брак                 1
9    женат / замужем                 0
10   женат / замужем                 0
11   женат / замужем                 0
12  гражданский брак                 1
13   женат / замужем                 0
14  гражданский брак                 1

family_status  family_status_id
21439        женат / замужем                 0
21440       гражданский брак                 1
21441  не женат / не замужем                 4
21442        женат / замужем                 0
21443  не женат / не замужем                 4
21444        женат / замужем                 0
21445        женат / замужем                 0
21446       гражданский брак                 1
21447        женат / замужем                 0
21448              в разводе                 3
21449       гражданский брак                 1
21450        женат / замужем                 0
21451       гражданский брак                 1
21452        женат / замужем                 0
21453        женат / замужем                 0

<div class="alert alert-info">
<b>Комментарий студента:</b>
<br>Теперь на основе нескольких условий в столбцах: 'education', 'education_id', обоснуем, что уровень образования (высшее, среднее и незаконченное высшее, столбец 'education') строго соответствует цифре (0, 1, 2) в столбце 'education_id', по заполнении условии истинности True, до удаления лишних столбцов: 'education', 'family_status'. Также и со столбцами: 'family_status', 'family_status_id'<br>  
</div>

In [57]:
part_education_if = ( ((part_education['education'] == 'высшее') & (part_education['education_id'] == 0)) | 
                      ((part_education['education'] == 'среднее') & (part_education['education_id'] == 1)) | 
                      ((part_education['education'] == 'неоконченное высшее') & (part_education['education_id'] == 2)) | 
                      ((part_education['education'] == 'начальное') & (part_education['education_id'] == 3)) | 
                      ((part_education['education'] == 'ученая степень') & (part_education['education_id'] == 4)))

display(part_education_if.head(15))  
display(part_education_if.tail(15))     

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
dtype: bool

21439    True
21440    True
21441    True
21442    True
21443    True
21444    True
21445    True
21446    True
21447    True
21448    True
21449    True
21450    True
21451    True
21452    True
21453    True
dtype: bool

In [58]:
part_family_status_if = ( ((part_family_status['family_status'] == "женат / замужем") & (part_family_status['family_status_id'] == 0)) | 
                          ((part_family_status['family_status'] == "гражданский брак") & (part_family_status['family_status_id'] == 1)) | 
                          ((part_family_status['family_status'] == "вдовец / вдова") & (part_family_status['family_status_id'] == 2)) | 
                          ((part_family_status['family_status'] == "в разводе") & (part_family_status['family_status_id'] == 3)) | 
                          ((part_family_status['family_status'] == "не женат / не замужем") & (part_family_status['family_status_id'] == 4)) )

display(part_family_status_if.head(15))  
display(part_family_status_if.tail(15))      

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
dtype: bool

21439    True
21440    True
21441    True
21442    True
21443    True
21444    True
21445    True
21446    True
21447    True
21448    True
21449    True
21450    True
21451    True
21452    True
21453    True
dtype: bool

<div class="alert alert-info">
<b>Комментарий студента:</b>
<br>Судя с взаимодействием пары столбцов: 'education' и 'education_id', 'family_status' и 'family_status_id', наименование уровня образования и статус семейного положения строго соответствует с определенной цифрой столбцов 'education_id' и 'family_status_id' (соответственно). Поэтому столбцы 'education' и 'education_id' будем удалять с помощью метода drop(columns = [<i>Названия колонок</i>]). <br>  
</div>

In [59]:
data = data.drop(columns = ['education', 'family_status'])
display(data.head(30))

children  days_employed  dob_years  education_id  family_status_id gender  \
0          1    8437.673028         42             0                 0      F   
1          1    4024.803754         36             1                 0      F   
2          0    5623.422610         33             1                 0      M   
3          3    4124.747207         32             1                 0      M   
4          0     932.235814         53             1                 1      F   
5          0     926.185831         27             0                 1      M   
6          0    2879.202052         43             0                 0      F   
7          0     152.779569         50             1                 0      M   
8          2    6929.865299         35             0                 1      F   
9          0    2188.756445         41             1                 0      M   
10         2    4171.483647         36             0                 0      M   
11         0     792.701887         40             1                 0      F   
12         0    1203.369529         65             1                 1      M   
13         0    1846.641941         54             2                 0      F   
14         0    1844.956182         56             0                 1      F   
15         1     972.364419         26             1                 0      F   
16         0    1719.934226         35             1                 0      F   
17         0    2369.999720         33             0                 1      M   
18         0    1096.660649         53             1                 2      F   
19         0   10038.818549         48             1                 3      F   
20         1    1311.604166         36             1                 0      M   
21         1     253.685166         33             1                 1      F   
22         1    1766.644138         24             1                 1      F   
23         0     272.981385         21             0                 1      M   
24         1     927.539597         57             1                 4      F   
25         0     996.023258         67             1                 0      M   
26         0    1203.369529         41             1                 0      M   
27         0     529.191635         28             0                 0      M   
28         1     717.274324         26             0                 0      F   
29         0    1203.369529         63             1                 4      F   

    income_type  debt  total_income                                 purpose  
0     сотрудник     0        253875                           покупка жилья  
1     сотрудник     0        112080                 приобретение автомобиля  
2     сотрудник     0        145885                           покупка жилья  
3     сотрудник     0        267628              дополнительное образование  
4     пенсионер     0        158616                         сыграть свадьбу  
5     компаньон     0        255763                           покупка жилья  
6     компаньон     0        240525                       операции с жильем  
7     сотрудник     0        135823                             образование  
8     сотрудник     0         95856                   на проведение свадьбы  
9     сотрудник     0        144425                 покупка жилья для семьи  
10    компаньон     0        113943                    покупка недвижимости  
11    сотрудник     0         77069       покупка коммерческой недвижимости  
12    пенсионер     0        145017                         сыграть свадьбу  
13    сотрудник     0        130458                 приобретение автомобиля  
14    компаньон     1        165127              покупка жилой недвижимости  
15    сотрудник     0        116820  строительство собственной недвижимости  
16    сотрудник     0        289202                            недвижимость  
17    сотрудник     0         90410              строительство недвижимости  
18    пенс

### 0.7 Шаг 2.6. Категоризация дохода.

In [60]:
def total_income_category(total_income):
    
    if((total_income >= 0) & (total_income <= 30000)):
        return 'E'
    elif((total_income > 30000) & (total_income <= 50000)):
        return 'D'
    elif((total_income > 50000) & (total_income <= 200000)):
        return 'C'
    elif((total_income > 200000) & (total_income <= 1000000)):
        return 'B'
    else:
        return 'A'   

<div class="alert alert-info">
<b>Комментарий студента:</b>
<br>Сначала уже написанную функцию total_income_category() для определения категории уровня, с указанными значениями доходов, используем в качестве проверки отдельных значений такие, как: 
    <br>'A' (0 <= total_income <= 30000), 
    <br>'B' (30000 < total_income <= 50000), 
    <br>'C' (50000 < total_income <= 200000), 
    <br>'D' (200000 < total_income <= 1000000) и 
    <br>'E' (total_income > 1000000), 
<br>которые были сделаны в виде списков со значениями: 25000, 235000, 2570000. А также применим эту функцию в датафрейм data, с помощью функции apply().<br>  
</div>

In [61]:
total_income_1 = 25000
total_income_2 = 235000
total_income_3 = 2570000

total_income = [total_income_1, total_income_2, total_income_3]
total_income_categ = [total_income_category(total_income_1), total_income_category(total_income_2), total_income_category(total_income_3)]

total_income

[25000, 235000, 2570000]

In [62]:
total_income_categ

['E', 'B', 'A']

In [63]:
data['total_income_category'] = data['total_income'].apply(total_income_category)
display(data.head(60))

children  days_employed  dob_years  education_id  family_status_id gender  \
0          1    8437.673028         42             0                 0      F   
1          1    4024.803754         36             1                 0      F   
2          0    5623.422610         33             1                 0      M   
3          3    4124.747207         32             1                 0      M   
4          0     932.235814         53             1                 1      F   
5          0     926.185831         27             0                 1      M   
6          0    2879.202052         43             0                 0      F   
7          0     152.779569         50             1                 0      M   
8          2    6929.865299         35             0                 1      F   
9          0    2188.756445         41             1                 0      M   
10         2    4171.483647         36             0                 0      M   
11         0     792.701887         40             1                 0      F   
12         0    1203.369529         65             1                 1      M   
13         0    1846.641941         54             2                 0      F   
14         0    1844.956182         56             0                 1      F   
15         1     972.364419         26             1                 0      F   
16         0    1719.934226         35             1                 0      F   
17         0    2369.999720         33             0                 1      M   
18         0    1096.660649         53             1                 2      F   
19         0   10038.818549         48             1                 3      F   
20         1    1311.604166         36             1                 0      M   
21         1     253.685166         33             1                 1      F   
22         1    1766.644138         24             1                 1      F   
23         0     272.981385         21             0                 1      M   
24         1     927.539597         57             1                 4      F   
25         0     996.023258         67             1                 0      M   
26         0    1203.369529         41             1                 0      M   
27         0     529.191635         28             0                 0      M   
28         1     717.274324         26             0                 0      F   
29         0    1203.369529         63             1                 4      F   
30         1     919.401832         62             1                 0      F   
31         0    1682.083438         47             3                 0      F   
32         0    4649.910832         34             1                 1      F   
33         0    1548.637544         48             1                 0      F   
34         0    4488.067031         35             1                 0      F   
35         0    1079.509787         68             1                 1      M   
36         0     176.216688         33             1                 4      M   
37         0    6448.810860         43             0                 1      F   
38         0     597.881827         25             0                 4      M   
39         0     650.587796         31             0                 1      F   
40         0    1030.362606         30             1                 4      M   
41         0    1203.369529         50             1                 0      F   
42         0    1257.496190         20             2                 4      F   
43         0    4375.681384         43             2                 3      F   
44         1    1362.041728         26             1                 0      F   
45         1    1039.451741         49             1                 4      F   
46         2    2262.712304         37             1                 0      F   
47         1    2689.137274         33             0                 1      M   
48         0    3341.067886        

<div class="alert alert-info">
<b>Комментарий студента:</b>
<br>Затем сделаем выборку, с помощью метода .query() по строкам 'total_income_category' из меньшинства значений: 'A', 'D' и 'E' и сгруппируе
    Сначала уже написанную функцию total_income_category() для определения категории уровня доходов используем в качестве проверки отдельных значений такие, как: 'A', 'B', 'C', 'D' и 'E', которые были сделаны в виде списков. А также применим эту функцию в датафрейм data, с помощью функции apply().<br>  
</div>

In [64]:
data.query("total_income_category == 'A'")

children  days_employed  dob_years  education_id  family_status_id  \
1590          1    1283.436610         53             0                 0   
2224          1    4614.851849         42             0                 0   
4127          0    7992.968249         52             0                 0   
4412          0     542.321356         45             1                 1   
7441          0    8626.777234         39             1                 3   
9146          0      65.163190         52             0                 0   
9159          1    5248.554336         35             1                 1   
9856          2    3092.259823         56             0                 0   
9989          0    1979.388318         58             1                 0   
11052         1    1851.200013         36             0                 1   
12390         0    1477.438114         44             0                 0   
13066         1    3531.320534         54             0                 3   
15015         2    1654.855987         39             0                 0   
15177         0    2009.086175         34             1                 0   
15234         1   10207.448165         64             0                 3   
17137         0    5734.127087         42             0                 1   
17460         0    2285.476482         43             1                 0   
18301         0    5536.801152         35             0                 1   
18306         1    3173.282035         41             0                 4   
18321         1     333.935516         41             0                 1   
18715         2    1019.604773         43             0                 0   
19283         3    1733.364682         34             0                 0   
19548         1    2577.664662         39             0                 0   
19754         0    2672.323106         50             0                 0   
20742         0    4719.273476         61             1                 4   

      gender income_type  debt  total_income  \
1590       F   компаньон     0       1089120   
2224       M   сотрудник     0       1278622   
4127       F   компаньон     0       1004476   
4412       M   компаньон     1       1030899   
7441       F   сотрудник     0       1240165   
9146       M   компаньон     0       1006468   
9159       M   сотрудник     0       1726276   
9856       M   сотрудник     0       1103455   
9989       M   сотрудник     0       1097954   
11052      F   сотрудник     0       1286280   
12390      M   компаньон     0       2265604   
13066      F   компаньон     0       1128836   
15015      M   сотрудник     0       1058193   
15177      F   сотрудник     0       1172459   
15234      M   компаньон     0       1350245   
17137      M   компаньон     0       1711309   
17460      M   компаньон     0       1597613   
18301      F   компаньон     0       1027742   
18306      F   компаньон     0       1427934   
18321      M   компаньон     0       1551152   
18715      M   компаньон     0       1092608   
19283      M   сотрудник     0       1091627   
19548      M   компаньон     1       2200852   
19754      F   компаньон     0       1223042   
20742      F   сотрудник     0       1715018   

                                     purpose total_income_category  
1590                   на покупку автомобиля                     A  
2224                           покупка жилья                     A  
4127   операции с коммерческой недвижимостью                     A  
4412                  профильное образование                     A  
7441                    покупка недвижимости                     A  
9146                       операции с жильем                     A  
9159              дополнительное образование                     A  
9856                 покупка жилья для семьи                     A  
9989                    покупка своего жилья                     A  
11052      покупка коммерческой недвижимости                     

In [65]:
data.query("total_income_category == 'D'")

children  days_employed  dob_years  education_id  family_status_id  \
49            0    1181.443228         54             1                 0   
71            0     926.338438         62             1                 0   
89            0      72.625785         42             1                 1   
119           0    1047.093504         60             1                 4   
152           1    3597.776388         39             1                 0   
...         ...            ...        ...           ...               ...   
21315         0     982.552640         71             1                 0   
21391         0    1446.326113         45             1                 0   
21396         0     926.193941         59             1                 0   
21404         0    1000.584401         52             1                 0   
21419         2    1867.006757         32             1                 0   

      gender income_type  debt  total_income  \
49         F   сотрудник     0         44591   
71         F   пенсионер     0         43929   
89         F   компаньон     0         49463   
119        F   пенсионер     0         31534   
152        F   компаньон     0         40891   
...      ...         ...   ...           ...   
21315      F   пенсионер     0         41411   
21391      F   сотрудник     0         34472   
21396      F   пенсионер     0         47388   
21404      F   пенсионер     1         48239   
21419      F   сотрудник     0         34767   

                                     purpose total_income_category  
49                                автомобиль                     D  
71                                автомобили                     D  
89          сделка с подержанным автомобилем                     D  
119        покупка коммерческой недвижимости                     D  
152                     покупка своего жилья                     D  
...                                      ...                   ...  
21315                 профильное образование                     D  
21391                покупка жилья для сдачи                     D  
21396                  получение образования                     D  
21404                        свой автомобиль                     D  
21419  операции с коммерческой недвижимостью                     D  

[350 rows x 11 columns]

In [66]:
data.query("total_income_category == 'E'")

children  days_employed  dob_years  education_id  family_status_id  \
934           0     954.118799         69             1                 0   
1184          0    1100.206018         55             1                 1   
1598          0     985.550970         68             1                 1   
4055          0    1058.601363         64             1                 0   
8264          0     615.774147         46             1                 0   
9060          0     934.117166         60             1                 4   
10053         0    4959.893007         43             1                 0   
10606         0    1056.613767         67             1                 0   
10863         0     951.661696         71             1                 0   
12032         1     971.407148         55             3                 1   
12983         0    1012.900244         37             1                 1   
14247         0     949.595764         61             1                 0   
14555         0     984.161806         57             1                 0   
14889         2    1440.353367         28             1                 1   
15358         1    2945.051315         45             1                 0   
16138         1    3642.820023         52             1                 0   
16558         0     241.247456         49             1                 1   
17840         0     927.644417         59             1                 0   
18461         0    1015.009115         60             1                 0   
18619         1    1953.777603         50             1                 0   
20151         0    1044.566898         59             1                 0   
21122         0     987.153356         55             1                 4   

      gender  income_type  debt  total_income  \
934        F    пенсионер     0         29426   
1184       M    пенсионер     0         29749   
1598       M    пенсионер     0         21695   
4055       F    пенсионер     1         29154   
8264       F    сотрудник     0         26533   
9060       F    пенсионер     0         24457   
10053      F    сотрудник     0         25227   
10606      F    пенсионер     0         27776   
10863      M    пенсионер     0         22472   
12032      F    пенсионер     0         25308   
12983      M    пенсионер     0         21205   
14247      F    пенсионер     0         21895   
14555      F    пенсионер     1         20667   
14889      F    сотрудник     0         28092   
15358      F    сотрудник     0         26329   
16138      M    сотрудник     0         21367   
16558      F    компаньон     0         28702   
17840      F    пенсионер     0         27414   
18461      F    пенсионер     0         23844   
18619      F  госслужащий     0         29200   
20151      F    пенсионер     0         29067   
21122      M    пенсионер     0         27907   

                                      purpose total_income_category  
934                              недвижимость                     E  
1184                    на проведение свадьбы                     E  
1598                    на проведение свадьбы                     E  
4055               строительство недвижимости                     E  
8264        покупка коммерческой недвижимости                     E  
9060    операции с коммерческой недвижимостью                     E  
10053                      высшее образование                     E  
10606                   заняться образованием                     E  
10863         операции со своей недвижимостью                     E  
12032              дополнительное образование                     E  
12983            заняться высшим образованием                     E  
14247                            недвижимость                     E  
14555                            недвижимость                     E  
14889                   на проведение свадьбы                     E  
15358  строительство собственной недвижимости            

In [67]:
data.groupby('total_income_category')['total_income_category'].count()

total_income_category
A       25
B     5041
C    16016
D      350
E       22
Name: total_income_category, dtype: int64

<div class="alert alert-info">
<b>Комментарий студента:</b> <i>(Вывод к пункту 7, шага №2.)</i>
<br>Судя по группировки уже созданного столбца 'total_income_category', что большинство клиентов банка со средне и немного выше средне ежемесячным доходом, т. е. по категориям 'С', 'B'. Также можно сделать вывод, о том, что те люди, которые имеют доход ниже среднего не могут себе позволить кредит, с опасением, что не смогут вернуть кредит вовремя, поэтому банки крайне неохотно выдают кредиты. И клиенты с ежемесячным доходом более миллиона рублей 'A' не будут брать кредиты без острой необходимости, даже на недвижимость.<br>  
</div>

### 0.8 Шаг 2.7. Категоризация целей кредита.

<div class="alert alert-info">
<b>Комментарий студента:</b>
<br>Для того, чтобы заменить значения столбца 'purpose', нужно сначала вывести список всех уникальных значений, для того чтобы установить зависимость для определения и вставки значений в новый столбец: 'purpose_category'.<br>  
</div>

In [68]:
data['purpose'].unique()

array(['покупка жилья', 'приобретение автомобиля',
       'дополнительное образование', 'сыграть свадьбу',
       'операции с жильем', 'образование', 'на проведение свадьбы',
       'покупка жилья для семьи', 'покупка недвижимости',
       'покупка коммерческой недвижимости', 'покупка жилой недвижимости',
       'строительство собственной недвижимости', 'недвижимость',
       'строительство недвижимости', 'на покупку подержанного автомобиля',
       'на покупку своего автомобиля',
       'операции с коммерческой недвижимостью',
       'строительство жилой недвижимости', 'жилье',
       'операции со своей недвижимостью', 'автомобили',
       'заняться образованием', 'сделка с подержанным автомобилем',
       'получение образования', 'автомобиль', 'свадьба',
       'получение дополнительного образования', 'покупка своего жилья',
       'операции с недвижимостью', 'получение высшего образования',
       'свой автомобиль', 'сделка с автомобилем',
       'профильное образование', 'высшее об

<div class="alert alert-info">
<b>Комментарий студента:</b>
<br>Мы видим, что для опредения подходящих значений, для вставки категорий в столбец 'purpose_category', нужно взять значения слов-маркеров (без окончаний!) для из уникальных значений столбцов 'purpose', например: 'недвижимост', 'жиль', 'автомобил', 'свадьб' и для наглядности: сгруппируем значения столбца 'purpose' в четыре списка: data_flat, data_vachile, data_wedding, data_education.<br>  
А затем создадим функцию purpose_function для категоризации цели кредита со следующими значениями: 'операции с автомобилем', 'операции с недвижимостью', 'проведение свадьбы', 'получение образования' и обновляем все значения, из только что созданной функции purpose_function в столбце 'purpose', с помощью функции apply() (как было выполнено в шаге 2.6).
<br>Под конец создадим группировку по столбцу 'purpose' с подсчётом количества всех перечисленных значений, с дополнительным методом count() .<br>  
</div>

In [69]:
data_flat = []
data_vachile = []
data_wedding = []
data_education = []

for item in data['purpose'].unique():
    if(('недвижимост' in item) |  ('жиль' in item)):
        data_flat.append(item)
    elif('автомобил' in item):
        data_vachile.append(item)
    elif('свадьб' in item):
        data_wedding.append(item)
    else:
        data_education.append(item)
        
data_flat

['покупка жилья',
 'операции с жильем',
 'покупка жилья для семьи',
 'покупка недвижимости',
 'покупка коммерческой недвижимости',
 'покупка жилой недвижимости',
 'строительство собственной недвижимости',
 'недвижимость',
 'строительство недвижимости',
 'операции с коммерческой недвижимостью',
 'строительство жилой недвижимости',
 'жилье',
 'операции со своей недвижимостью',
 'покупка своего жилья',
 'операции с недвижимостью',
 'покупка жилья для сдачи',
 'ремонт жилью']

In [70]:
data_vachile

['приобретение автомобиля',
 'на покупку подержанного автомобиля',
 'на покупку своего автомобиля',
 'автомобили',
 'сделка с подержанным автомобилем',
 'автомобиль',
 'свой автомобиль',
 'сделка с автомобилем',
 'на покупку автомобиля']

In [71]:
data_wedding

['сыграть свадьбу', 'на проведение свадьбы', 'свадьба']

In [72]:
data_education

['дополнительное образование',
 'образование',
 'заняться образованием',
 'получение образования',
 'получение дополнительного образования',
 'получение высшего образования',
 'профильное образование',
 'высшее образование',
 'заняться высшим образованием']

In [73]:
def purpose_function(old_genres):  # Функция для замены неявных дубликатов
    if(('недвижимост' in old_genres) |  ('жиль' in old_genres)):
        return 'операции с недвижимостью'
    elif('автомобил' in old_genres):
        return 'операции с автомобилем'
    elif('свадьб' in old_genres):
        return 'проведение свадьбы'
    else:
        return 'получение образования' 

In [74]:
data['purpose'] = data['purpose'].apply(purpose_function)
display(data.head(30))  

children  days_employed  dob_years  education_id  family_status_id gender  \
0          1    8437.673028         42             0                 0      F   
1          1    4024.803754         36             1                 0      F   
2          0    5623.422610         33             1                 0      M   
3          3    4124.747207         32             1                 0      M   
4          0     932.235814         53             1                 1      F   
5          0     926.185831         27             0                 1      M   
6          0    2879.202052         43             0                 0      F   
7          0     152.779569         50             1                 0      M   
8          2    6929.865299         35             0                 1      F   
9          0    2188.756445         41             1                 0      M   
10         2    4171.483647         36             0                 0      M   
11         0     792.701887         40             1                 0      F   
12         0    1203.369529         65             1                 1      M   
13         0    1846.641941         54             2                 0      F   
14         0    1844.956182         56             0                 1      F   
15         1     972.364419         26             1                 0      F   
16         0    1719.934226         35             1                 0      F   
17         0    2369.999720         33             0                 1      M   
18         0    1096.660649         53             1                 2      F   
19         0   10038.818549         48             1                 3      F   
20         1    1311.604166         36             1                 0      M   
21         1     253.685166         33             1                 1      F   
22         1    1766.644138         24             1                 1      F   
23         0     272.981385         21             0                 1      M   
24         1     927.539597         57             1                 4      F   
25         0     996.023258         67             1                 0      M   
26         0    1203.369529         41             1                 0      M   
27         0     529.191635         28             0                 0      M   
28         1     717.274324         26             0                 0      F   
29         0    1203.369529         63             1                 4      F   

    income_type  debt  total_income                   purpose  \
0     сотрудник     0        253875  операции с недвижимостью   
1     сотрудник     0        112080    операции с автомобилем   
2     сотрудник     0        145885  операции с недвижимостью   
3     сотрудник     0        267628     получение образования   
4     пенсионер     0        158616        проведение свадьбы   
5     компаньон     0        255763  операции с недвижимостью   
6     компаньон     0        240525  операции с недвижимостью   
7     сотрудник     0        135823     получение образования   
8     сотрудник     0         95856        проведение свадьбы   
9     сотрудник     0        144425  операции с недвижимостью   
10    компаньон     0        113943  операции с недвижимостью   
11    сотрудник     0         77069  операции с недвижимостью   
12    пенсионер     0        145017        проведение свадьбы   
13    сотрудник     0        130458    операции с автомобилем   
14    компаньон     1        165127  операции с недвижимостью   
15    сотрудник     0        116820  операции с недвижимостью   
16    сотрудник     0        289202  операции с недвижимостью   
17    сотрудник     0         90410  операции с недвижимостью   
18    пенсионер     0         56823    операции с автомобилем   
19    сотрудник     0        242831    операции с автомобилем   
20    сотрудник     0        209552  операции с недвижимостью   
21    сотрудник     0        131812    операции с автомобилем 

In [75]:
data.groupby('purpose')['purpose'].count()

purpose
операции с автомобилем       4306
операции с недвижимостью    10811
получение образования        4013
проведение свадьбы           2324
Name: purpose, dtype: int64

<div class="alert alert-info">
<b>Комментарий студента:</b> <i>(Вывод к пункту 7, шага 2.)</i>
<br>Судя, по количеству клиентов, преобладающее число клиентов, с целью которого берут кредиты - это операции с недвижимостью (другими словами берут ипотеку). С другими целями клиенты берут кредиты примерно 2,5 раза реже, чем по операции с недвижимостью (особенно редко берут кредиты на проведение свадьбы - примерно в 4 раза реже, чем операции с недвижимостью). Значит многие клиенты хоть в какой то мере знают себе цену к своим деньгам.<br>  
</div>

<div class="alert alert-info">
<b>Комментарий студента:</b>
<br>Перед тем, как создать финальную таблицу с использованием метода .pivot_table(), а также в качестве доказательства ответов на вопросы в шаге №3 и для составления вывода в шаге № 4, создаем столбец 'count' со всеми значениями 1, для подсчёта всех клиентов, которые попадают в ту или иную категорию из условий , которые были указаны в параметре 'index' и чтобы не отвлекаться на изменение пареметра значения: пропишем условие в параметре 'aggfunc' вместо 'sum' на 'count' (Параметры 'sum' и 'mean' отобразят разные результаты во всех столбцах, в отличие от параметра 'count' (посчёта количества заполненных строк в таблице), где отобразятся во всех столбцах одинаковые результаты.)).<br>  
</div>

In [76]:
data['count'] = 1
display(data.head(30))  

children  days_employed  dob_years  education_id  family_status_id gender  \
0          1    8437.673028         42             0                 0      F   
1          1    4024.803754         36             1                 0      F   
2          0    5623.422610         33             1                 0      M   
3          3    4124.747207         32             1                 0      M   
4          0     932.235814         53             1                 1      F   
5          0     926.185831         27             0                 1      M   
6          0    2879.202052         43             0                 0      F   
7          0     152.779569         50             1                 0      M   
8          2    6929.865299         35             0                 1      F   
9          0    2188.756445         41             1                 0      M   
10         2    4171.483647         36             0                 0      M   
11         0     792.701887         40             1                 0      F   
12         0    1203.369529         65             1                 1      M   
13         0    1846.641941         54             2                 0      F   
14         0    1844.956182         56             0                 1      F   
15         1     972.364419         26             1                 0      F   
16         0    1719.934226         35             1                 0      F   
17         0    2369.999720         33             0                 1      M   
18         0    1096.660649         53             1                 2      F   
19         0   10038.818549         48             1                 3      F   
20         1    1311.604166         36             1                 0      M   
21         1     253.685166         33             1                 1      F   
22         1    1766.644138         24             1                 1      F   
23         0     272.981385         21             0                 1      M   
24         1     927.539597         57             1                 4      F   
25         0     996.023258         67             1                 0      M   
26         0    1203.369529         41             1                 0      M   
27         0     529.191635         28             0                 0      M   
28         1     717.274324         26             0                 0      F   
29         0    1203.369529         63             1                 4      F   

    income_type  debt  total_income                   purpose  \
0     сотрудник     0        253875  операции с недвижимостью   
1     сотрудник     0        112080    операции с автомобилем   
2     сотрудник     0        145885  операции с недвижимостью   
3     сотрудник     0        267628     получение образования   
4     пенсионер     0        158616        проведение свадьбы   
5     компаньон     0        255763  операции с недвижимостью   
6     компаньон     0        240525  операции с недвижимостью   
7     сотрудник     0        135823     получение образования   
8     сотрудник     0         95856        проведение свадьбы   
9     сотрудник     0        144425  операции с недвижимостью   
10    компаньон     0        113943  операции с недвижимостью   
11    сотрудник     0         77069  операции с недвижимостью   
12    пенсионер     0        145017        проведение свадьбы   
13    сотрудник     0        130458    операции с автомобилем   
14    компаньон     1        165127  операции с недвижимостью   
15    сотрудник     0        116820  операции с недвижимостью   
16    сотрудник     0        289202  операции с недвижимостью   
17    сотрудник     0         90410  операции с недвижимостью   
18    пенсионер     0         56823    операции с автомобилем   
19    сотрудник     0        242831    операции с автомобилем   
20    сотрудник     0        209552  операции с недвижимостью   
21    сотрудник     0        131812    операции с автомобилем 

<div class="alert alert-info">
<b>Комментарий студента:</b>
<br>Затем создаём шесть сводных таблиц с использованием метода .pivot_table(): 
    <br><br>первая таблица - три столбца таблицы будут выступать, в качестве индексов (параметр 'index', в форме списка) - это 'purpose_category', 'total_income_category', 'debt' (конкретные цели для получения кредита, оценка ежемесячного дохода и наличие задолженности по возврату кредитов) с параметром для вычисления столбцов aggfunc, где содержатся значения типа данных 'int' или 'float' и, группируя по значениям из столбцов в параметре 'index', вычисляет сумму ('sum') числовые значения из остальных столбцов;   
    <br><br>вторая таблица - эта уже главная финальная таблица, такая же первая таблица, которая характеризует клиента банка, цель получения кредита и отсутствие задолженности, но отличия будут в добавлении конкретных столбцов, в виде списков, с числовыми значениями (т.е. 'value'), а именно: 'children', 'family_status_id', 'total_income' (для анализа данных, где требуется обоснования ответов на вопросы в шаге №3 и сформулирования общего вывода в шаге №4), а также единичный столбец 'count' - для посчёта количества клиентов, подходящих под параметров в кажой категории из столбцов из параметра 'index'.
</div>

<div class="alert alert-info">
<b>Комментарий студента:</b>
<br>А далее: все последние четыре таблицы, вполне схожие со второй таблицей, но они регулируют зависимость между двумя факторами, чтобы легче анализовать результат, отвечая на вопросы из шага № 3, которые будут размещены в список параметра 'index', а остальные имена столбцов с числовыми типами данных будут размещаться в список параметра 'value': 
    <br><br>третья таблица - 'index': 'children' и 'debt' , 'value' : 'count', 'family_status_id' и 'total_income';
    <br><br>четвёртая таблица - 'index': 'family_status_id' и 'debt', 'value' : 'count', 'children' и 'total_income';
    <br><br>пятая таблица - 'index': 'total_income_category' и 'debt', 'value' : 'count', 'children', 'family_status_id' и 'total_income';
    <br><br>шестая таблица - 'index': 'purpose' и 'debt', 'value' : 'count', 'family_status_id' и 'total_income'.<br>  
</div>

In [77]:
data_pivot_sum_1 = data.pivot_table(index=['purpose', 'total_income_category', 'debt'], aggfunc = 'sum')
display(data_pivot_sum_1.head(30))             

children  count  \
purpose                  total_income_category debt                    
операции с автомобилем   A                     0            2      2   
                         B                     0          479    945   
                                               1           54     86   
                         C                     0         1301   2892   
                                               1          162    307   
                         D                     0           27     62   
                                               1            7     10   
                         E                     0            2      2   
операции с недвижимостью A                     0           11     16   
                                               1            1      1   
                         B                     0         1201   2396   
                                               1           90    172   
                         C                     0         3523   7446   
                                               1          336    601   
                         D                     0           62    162   
                                               1            4      6   
                         E                     0            1      9   
                                               1            0      2   
получение образования    A                     0            3      3   
                                               1            0      1   
                         B                     0          394    827   
                                               1           38     70   
                         C                     0         1319   2734   
                                               1          158    297   
                         D                     0           39     74   
                                               1            0      2   
                         E                     0            1      5   
проведение свадьбы       A                     0            1      2   
                         B                     0          267    517   
                                               1            8     28   

                                                     days_employed  dob_years  \
purpose                  total_income_category debt                             
операции с автомобилем   A                     0      4.456719e+03         94   
                         B                     0      2.162685e+06      40309   
                                               1      1.552595e+05       3511   
                         C                     0      5.622296e+06     127552   
                                               1      5.511943e+05      12188   
                         D                     0      1.159284e+05       2971   
                                               1      1.089203e+04        476   
                         E                     0      5.596598e+03        102   
операции с недвижимостью A                     0      6.140566e+04        763   
                                               1      2.577665e+03         39   
                         B                     0      5.553674e+06     101392   
                                               1      3.153372e+05       6900   
                         C                     0      1.480239e+07     324466   
                                               1      9.078869e+05      24171   
                         D                     0      2.728021e+05       8071   
                                               1      1.417881e+04        285   
                         E                     0      1.039705e+04        526   
                                               1      2.042763e+03        121   
получение образования    A                     0      8.912496e+03        108   
                                               

In [78]:
data_pivot_sum_2 = data.pivot_table(index=['purpose', 'total_income_category', 'debt'], values=['count', 'children', 'family_status_id', 'total_income'], aggfunc='sum')
display(data_pivot_sum_2.head(30))        

children  count  \
purpose                  total_income_category debt                    
операции с автомобилем   A                     0            2      2   
                         B                     0          479    945   
                                               1           54     86   
                         C                     0         1301   2892   
                                               1          162    307   
                         D                     0           27     62   
                                               1            7     10   
                         E                     0            2      2   
операции с недвижимостью A                     0           11     16   
                                               1            1      1   
                         B                     0         1201   2396   
                                               1           90    172   
                         C                     0         3523   7446   
                                               1          336    601   
                         D                     0           62    162   
                                               1            4      6   
                         E                     0            1      9   
                                               1            0      2   
получение образования    A                     0            3      3   
                                               1            0      1   
                         B                     0          394    827   
                                               1           38     70   
                         C                     0         1319   2734   
                                               1          158    297   
                         D                     0           39     74   
                                               1            0      2   
                         E                     0            1      5   
проведение свадьбы       A                     0            1      2   
                         B                     0          267    517   
                                               1            8     28   

                                                     family_status_id  \
purpose                  total_income_category debt                     
операции с автомобилем   A                     0                    4   
                         B                     0                  866   
                                               1                   86   
                         C                     0                 2865   
                                               1                  388   
                         D                     0                   44   
                                               1                    8   
                         E                     0                    0   
операции с недвижимостью A                     0                   15   
                                               1                    0   
                         B                     0                 2278   
                                               1                  186   
                         C                     0                 7256   
                                               1                  618   
                         D                     0                  120   
                                               1                    4   
                         E                     0                    8   
                                               1                    0   
получение образования    A                     0                    1   
                                               1                    1   
                         B                     0                  757   
                                               1                   84

In [81]:
data_pivot_sum_debt_1 = data.pivot_table(index=['children', 'debt'], values=['count', 'family_status_id', 'total_income'], aggfunc='sum')
display(data_pivot_sum_debt_1.head(30))   

count  family_status_id  total_income
children debt                                       
0        0     13028             14484    2128906395
         1      1063              1340     170285484
1        0      4410              3523     745606925
         1       445               403      72672413
2        0      1926               885     326595940
         1       202               103      33259446
3        0       303               118      55084094
         1        27                15       4016693
4        0        37                17       6164615
         1         4                 4        649576
5        0         9                 2       1508455

In [82]:
data_pivot_sum_debt_2 = data.pivot_table(index=['family_status_id', 'debt'], values=['count', 'children', 'total_income'], aggfunc='sum')
display(data_pivot_sum_debt_2.head(30))   

children  count  total_income
family_status_id debt                               
0                0         6460  11408    1905233490
                 1          606    931     151492554
1                0         1712   3763     622286401
                 1          208    388      61186864
2                0          138    896     128537550
                 1           13     63       9351988
3                0          479   1110     186864514
                 1           40     85      13414810
4                0          575   2536     420944469
                 1           79    274      45437396

In [84]:
data_pivot_sum_debt_3 = data.pivot_table(index=['total_income_category', 'debt'], values=['count', 'children', 'family_status_id', 'total_income'], aggfunc='sum')
display(data_pivot_sum_debt_3.head(30))   

children  count  family_status_id  total_income
total_income_category debt                                                 
A                     0           17     23                22      30246198
                      1            1      2                 1       3231751
B                     0         2341   4685              4418    1343676552
                      1          190    356               384     100672521
C                     0         6860  14656             14335    1875310595
                      1          740   1360              1461     176029648
D                     0          140    329               240      14115414
                      1           15     21                19        899871
E                     0            6     20                14        517665
                      1            0      2                 0         49821

In [85]:
data_pivot_sum_debt_4 = data.pivot_table(index=['purpose', 'debt'], values=['count', 'family_status_id', 'total_income'], aggfunc='sum')
display(data_pivot_sum_debt_4.head(30))   

count  family_status_id  total_income
purpose                  debt                                       
операции с автомобилем   0      3903              3779     647017183
                         1       403               482      64367144
операции с недвижимостью 0     10029              9677    1671713261
                         1       782               808     129220389
получение образования    0      3643              3435     592418474
                         1       370               389      59412983
проведение свадьбы       0      2138              2138     352717506
                         1       186               186      27883096

###  0.9  Ответы на вопросы.

##### 0.9.0.1 Вопрос 1:

Судя по таблице № 3, составленной по методу .pivot_table(), имеется зависимость между количеством детей и возвратом кредита в срок.

Формулируется однозначным утверждением: чем меньше количество детей у данных клиентов банка, тем выше вероятность возрата кредита в срок.

Потому что, у клиентов банка, которых нет детей, они тратят только на свои (а может и для супруги/супруга) основные социально-бытовые нужды, помимо самого погашения кредита, т.е. им не придётся пратить за алименты и расходы, связанные с нормальным жизнеобеспечением детей. 

##### 0.9.0.2 Вопрос 2:

Судя по таблице № 4, составленной по методу .pivot_table(), имеется неявная зависимость между семейным положением и возвратом кредита в срок.

Формулируется данным утверждением: большинство клиентов банка - это люди, которые имеют супружеские связи у данных клиентов банка и у них больше вероятность возрата кредита в срок. А неявная зависимость, потому что среди клиентов банка, которые уже имели супружеские связи, а теперь остались одни - скорее исключение, чем правило.  

Скорее всего, это связано с тем, что если клиент банка - многодетный семьянин, то ему нужно зарабатывать больше денег, чтобы обеспечивать супругу (или супруга) и детей (если они есть) (редкий позитивный случай: если он живёт на приусадебнем участке или у него есть дача (в СНТ, в селе или в деревне), то он может прокормить супругу (или супруга) на своём хозяйстве), то скорее он сможет заплатить за долги по кредитам, но если его неожиданно сократили на работе, то он может попасть в зоне риска должников.

##### 0.9.0.3 Вывод 3:

Судя по таблицам № 2 и 5, составленной по методу .pivot_table(), имеется неявная зависимость между уровнем дохода и возвратом кредита в срок. 

Формулируется следующим однозначным утверждением: чем выше уровень дохода у данных клиентов банка (не ниже уровня C, среди них большинство клиентов имеют категорию по уровню доходов 'С' и 'В'), тем больше вероятность возрата кредита в срок. А неявная зависимость, свидетельствует о том, что категории 'A', 'D', 'E' - это редкость, чем правило, потому что с доходами свыше миллиона рублей в месяц (категория 'A') могут похвастаться не многие, так как миллиона рублей в месяц могут зарабатывать только директорами, начальниками, топ-менеджерами в ведущих и иностранных компаниях, крупнейшими бизнесменами или депутатами в партийных номерклуатурах, а доходы в 50000 рублей в месяц и менее могут не потянуть на погашение кредитов, после оплаты социально-бытовых нужд и могут оказаться в должниках. 

Это очевидный факт, поскольку клиент всегда может расплатиться с банком по кредиту, в отличие от ситуации, когда он меньше получает, то он не может погасить долги, и если он сможет, то вынужден жить в коммуналке, на хлебе и воде, чтобы не оказаться должником.

##### 0.9.0.4 Вопрос 4:

Судя по таблицам №2 и 6, составленной по методу .pivot_table(), большинство клиентов банка обращаются за кредитами, с целью получения или другими оперциями с недвижимостью, у которых нет задолженности по возврату кредитов, а самая неохотная цель для получения кредита - это проведение свадьбы, у тех клиентов, которые уже имели (или имеют) задолженность (-и) по кредиту. 

Поскольку люди не могут прожить без еды, здоровья и жилья, если первыми двумя пунктами они могут себе по своим средствам, а сразу заплатить за недвижимость могут позволить себе только единицы населения, не точно только клиентов банка, когда сделали прелобработку данных, а на остальные цели сами себе заработать, накопить, выбрать наиболее выгодные предложения по различным услугам, на осуществление мечты и купить.<br>

А проведение свадьбы - это далеко не самая важная обязанность для человека, тем более, если он - должник, который берёт кредит на осуществление свадьбы, то он полный глупец в своих поступках, так как сэкономить на свадьбе - это единственная ценность, из четырёх перечисленных которую можно (и нужно) экономить без ущерба для клиента банка, в отличие от недвижимости (где нужно выбирать от расположения на территории, чтобы удобно ездить на работу до дополнительной инфраструктуры близкое расположение до станции метро, парка или магазинов), от автомобиля (чтобы не выбрать т.е. битую машину, где она побывала в ДТП, которую внешне и по документам пробразили, как в фразеологизме, "в конфетку"), получение образование (теоретически и практически, возможно сэкономить, если это не связано, с обучаением новой профессии или поступлением в вузы (реже ссузы) на договорной основе, которое не оплачивает компания, в которой этот клиент работает или когда его дети пойдут учится в вузы - получать хорошее высшее образование).

## 1 Общий вывод:

Посмотрев, на главную сводную таблицу, то сразу увидим, что большинство людей стали оформлять кредиты, со средним уровнем дохода, которые не имеют детей и задолженности по возврату кредитов (необязательно молодые люди), чаще с целью покупки или различными операциями с недвижимостью (например: ремонт той самой недвижимости, а также покупка или ремонт дачи, гаража и т.д.), операции с автомобилем и на получение образования (в основном высшего образования).

Крайне редко люди оформляют кредиты на проведение свадьбы, особенно когда имели долги перед банком, по возврату кредитов, это говорит о том, что большинство людей стали более-менее финансово грамотными, по сравнению со второй половиной XX века, что сказывается не просто на кардинальное изменение законодательства нашей Родины, но социального строя и возможностей привелегий, например: во второй половине XX века самые крупные денежные расходы люди тратили автомобили (в основном для личного пользования) и на проведение свадьбы, а на сегодняшний день люди тратят больше всего денег на покупку недвижимости и автомобиля (и на состояние этой недвижимости).   